### ISSUE TITLE
[Panel] Isn't it possible to place field in on the settings page anymore?

### ISSUE THREAD

**Issue by bavarianbytes** [getkirby/kirby#1393] opened 2019-01-23 18:03 UTC
In version 2 fields of the site blueprint showed up on the settings page. That was great to place some website settings there.

Now they don't show up and, as far as i understand, i have to place them somewhere on the panel start page by myself, right?
So i created two tabs "dashboard" (for the page listing) and "settings" (for my website settings). As there is a menu item called "settings" in the header of the panel, that's a little confusing for users.

Any recommendations to do that better?

**Comment by distantnative** [comment] 2019-01-23 18:11
It is correct: As in Kirby 2 you can still use the `site.yml` for custom site-wide settings, data etc. In Kirby 3 you could say that the Dashboard and the `site.yml` view have been merged. Creating a tab (you could also name it "Config" or even something more specific to the data you want people to enter there) seems to be a good way to me.

The new Settings view (in the main menu) cannot be easily modified so far. This might change in a future 3.x version, but nothing confirmed yet.

**Comment by bavarianbytes** [comment] 2019-01-23 18:12
Ok, thanks!

**Closed as completed** 2019-01-23 18:41 UTC

**Comment by texnixe** [comment] 2019-02-19 23:54
I wonder if we should reopen this issue or move it to the ideas repo as this request has come up several times in the forum by now, @bastianallgeier, @distantnative ?

e.g. https://forum.getkirby.com/t/blueprint-for-settings-page/12918/4
