### ISSUE TITLE
Panel Bug with "Files" URL page

### ISSUE THREAD

**Issue by mrvicis** [getkirby/kirby#3187] opened 2021-03-02 09:26 UTC
**To Reproduce**  
1. Create any page with "Files" URL
2. Try to edit any text field on this page
3. All typed data will dissapear

Video:
![Mar-02-2021 12-53-54](https://user-images.githubusercontent.com/15743822/109630897-7b3e0c80-7b56-11eb-8714-6ac8b48d6728.gif)

**Kirby Version**  
3.5.3.1

**Console output**  
It seems Kirby is trying to lock/unlock "Files" page, but returns errors:

[Error] Failed to load resource: the server responded with a status of 400 () (lock, line 0)
[Error] Object
code: 400
details: [] (0)
exception: "Kirby\\Exception\\InvalidArgumentException"
file: "/kirby/src/Cms/Api.php"
key: "error.invalidArgument"
line: 141
message: "Invalid model type: ."
route: "(.*)/files/([a-zA-Z0-9\\.\\-_%= \\+\\@\\(\\)]+)"
status: "error"
Object Prototype
	onError (app.js:1:22082)
	(anonymous function) (app.js:1:17731)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJobWithoutPromise

**Comment by afbora** [comment] 2021-03-02 09:36
> Create any page with "Files" URL

Do you mean "files field"?

Can you elaborate a little more on the steps?

**Comment by afbora** [comment] 2021-03-02 10:02
It may be the most unusual bug I've seen on Kirby 😵

**Comment by mrvicis** [comment] 2021-03-02 10:07
I've tried to reproduce this bug on Kirby Demo, but there is no option to create 1st level page. 2st level pages with "Files" URL creates and edits correctly.

**Comment by bastianallgeier** [comment] 2021-03-02 10:10
I know why this bug is happening. /page/(:any)/files is a reserved route in our API and this probably collides with "files" as slug. We should either fix that or don't allow such reserved words for slugs.

**Comment by afbora** [comment] 2021-03-02 10:12
@bastianallgeier Yes but i guess this is related with files routes that relative: `(:all)/files`

_Edit: I guess I mean the same thing 😅_

**Comment by distantnative** [comment] 2021-07-18 15:44
@afbora seems to be fixed in 3.6.0-alpha.1 for me -  can you confirm this too?

**Comment by afbora** [comment] 2021-07-18 15:50
@distantnative Unfortunately i can still reproduce the issue on 3.6.0-alpha.1. Create page that have `files` slug in root (under site directly).

**Comment by distantnative** [comment] 2021-07-18 15:59
Ahh, I didn't catch that it needs to be below `site` directly. Yes, still see it too. It works for me with other subpages.
The route should work fine, otherwise we wouldn't see the page blueprint.

If I look at my console, I think the content lock API call fails and thus resets all unsaved changes immediately.

**Comment by bastianallgeier** [comment] 2021-09-30 07:28
✅

**Closed as completed by bastianallgeier** 2021-09-30 07:28 UTC
