### ISSUE TITLE
Ignore slug in unified "Change-Title" dialog when changing slugs is not allowed

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#3464] opened 2021-06-27 07:10 UTC
**Describe the bug**  
When users try to change titles while being disallowed to change the slug, this result in an error message when Kirby tries to autocorrect the slug (e.g. from underscore to dash).

This happens when a page slug contains an underscore (either because a page was created manually or a left-over from Kirby 2.

**Expected behavior**  
When changing slugs is not allowed, Kirby shouldn't try to autocorrect slugs in the changeTitle dialog.

**Screenshots**  

**Kirby Version**  
Presumably since Kirby 3.50, when the combined title/slug dialog was introduced.

**Additional context**  
https://forum.getkirby.com/t/you-are-not-allowed-to-change-the-url-appendix/22656

**Comment by afbora** [comment] 2021-06-27 09:31
I know why this issue happened. Because in `PageRenameDialog` we use always `sluggify()` method even with or without user permission.

We can fix this easily, but it is caused by not applying the necessary conditions for Kirby 3 to work correctly. Is it really a bug that needs to be fixed? 🤔

**Comment by distantnative** [comment] 2021-07-17 16:12
Is that problem still existing in 3.6.0-alpha with the new PHP-powered dialogs?

**Comment by afbora** [comment] 2021-07-17 17:54
@distantnative You were right! The issue is fixed in 3.6.0-alpha.1 ✅

**Comment by afbora** [comment] 2021-07-17 17:55
Do we need to add to Notion?

**Closed as completed by afbora** 2021-07-17 17:54 UTC

**Comment by lukasbestle** [comment] 2021-07-18 18:48
Good idea, ✅.
