### ISSUE TITLE
In a multi-language setting, a non-default page version can be accessed both with the default language slug and its own translated slug.

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2257] opened 2019-10-29 20:01 UTC
**Describe the bug**  
Already done in the title

**To Reproduce**  
1. Create a multi-language Starterkit with two languages
2. Change the slug of a page in the non-default language
3. Access the page on the frontend.
4. Then change the page slug to the original default language slug in the address bar
5. Instead of showing the error page, the same page is still shown.

**Expected behavior**  
The same page should not be available under two URLs.

**Screenshots**  

**Kirby Version**  
Tested with 3.3.0-rc-3 but also happens in 3.2.5 (other versions not tested yet, didn't happen in older versions, though, as far as I remember).

**Comment by bastianallgeier** [comment] 2019-10-30 09:48
It's probably a regression from v2 to v3

**Comment by texnixe** [comment] 2019-10-30 10:00
I checked out older versions and the same issue already existed in 3.0.0, so nothing introduced through recent changes.

**Comment by bastianallgeier** [comment] 2019-10-30 10:55
I shouldn't be happy about that. But somehow I am 😂

**Comment by neildaniels** [comment] 2020-04-17 00:31
I actually really like this current behavior—for 2 reasons.

1. It lets me view a translated version of a page quickly, by simply changing the first part of the URL. (Only from when you're starting at the default language version.)

2. It lets us translate slugs over time, and links to the original page continue to work. The is **extremely helpful**.

For example, assume there's a page at `us/sports/cycling`. We might get around to translating the main sports page from French (including the slug), so the cycling page could live at `fr/des-sports/cycling`. When we finally get around to translating the cycling page, it would be `/fr/des-sports/cyclisme`.

But it's so important that if someone _did_ go to the untranslated cycling page (but on the French site), the link they're at won't break.

It would be neat if Kirby would automatically redirect to the "real" URL. I currently just include a `canonical` meta tag for the real URL and I'm happy with that.

**Comment by lukasbestle** [comment] 2020-04-24 13:35
I agree with @neildaniels: If Kirby can avoid a 404 by mapping the request to the original language, I think it should absolutely do that.

However two things should happen:

- There should be a redirect from the URL with the default language slugs to the canonical URL. This redirect currently doesn't exist.
- Let's say I have a page `page1` with the translated slug `seite1` and another page `page2` with the translated slug `page1` **(!)**. If I request the translated page `/de/page1`, I'd always expect Kirby to favor the translated slugs over the default language slugs (i.e. the page `page2` should be served because it uses the slug `page1` in the current translation). This currently works and we should verify with the fix for this issue that this behavior stays the same.

**Comment by distantnative** [comment] 2020-10-03 19:38
@lukasbestle so this al boils down to your list, right? One actionable item with one consideration that we shouldn't break with our changes.

**Comment by neildaniels** [comment] 2020-10-03 19:48
Via work on the PR #2763, specifically: https://github.com/getkirby/kirby/pull/2763#issuecomment-675765087, I just want to point out that:

`$pages->find()`/`$pages->findByUri()`/`$pages->findById()` do _not_ prefer translated lookups.

I think there is an opportunity to formalize the behavior of `$pages->findByUri()` and `$pages->findById()` (because both of them don't really do lookups strictly by what they name says). They'd likely be breaking changes, and there'd have to be a decision on what behavior `$pages->find()` adopts.

I would expect `$pages->findByUri()` to at least match the way routing works.

**Comment by ancascres** [comment] 2021-05-19 12:47
Just with the same problem using Kirby.... Is there a solution? It would be great that it Kirby can not show a 404 page, then it could redirect to the original url depending on the language

**Comment by lukasbestle** [comment] 2021-05-22 14:53
@ancascres It's a bit difficult to get right. I think we have a good plan what the behavior should be, but implementing it without regressions elsewhere and without breaking changes is difficult. So far we didn't find the time to work on this.

**Comment by distantnative** [comment] 2021-07-19 16:08
@lukasbestle Given that https://github.com/getkirby/kirby/pull/2763 finally got merged with 3.6.0-alpha.1, I think what remains from this is your suggestion to rather redirect than deliver, right? If so, I would suggest opening a new issue for that - just to have a cleaner and easier understand issue (without having to read the whole thing again and again). Could still reference this issue for background context).

**Comment by lukasbestle** [comment] 2021-07-19 19:56
Moved to https://github.com/getkirby/kirby/issues/3550.

**Closed as completed by lukasbestle** 2021-07-19 19:56 UTC
