### ISSUE TITLE
Deleting site files (The page "null" cannot be found)

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1150] opened 2018-10-29 14:44 UTC
**Describe the bug**
Deleting file throws `The page "null" cannot be found` in panel.

**To Reproduce**
1. Go to file
2. Click on delete

**Error**
`The page "null" cannot be found`

**Kirby Version**
3.0.0-beta-6.9

**Comment by texnixe** [comment] 2018-10-29 16:04
I can't reproduce this. You are using an old version. Does this also happen with the latest nightly?

**Comment by H-i-red** [comment] 2018-10-29 21:16
Well I can.
Kirby version : **3.0.0-beta-6.12**
Browser: **Chrome**

**Comment by H-i-red** [comment] 2018-10-29 21:17
hmm interesting it only happens on `site` files, **NOT** on `page` files.

**Comment by bastianallgeier** [comment] 2018-10-30 15:13
Hm, I just tried but couldn't reproduce this either. Also not for site files. What's your site blueprint?

**Comment by H-i-red** [comment] 2018-10-30 18:16
In site.yml I have this:
```
tabs:
    files:
        label: Files
        icon: image
        sections:
            files:
                headline: Files
                type: files
                layout: list
                template: global
                text: "{{ file.name }}"
                info: "{{ file.extension }} / {{ file.niceSize }} / {{ file.dimensions }}"
```
Kirby Version : 3.0.0-beta-6.12
Mac, Chrome Version 70.0.3538.67

**Comment by H-i-red** [comment] 2018-10-30 18:19
Deleting a file gives me this url : `https://koda.dev/cp/pages/null`
And the following error : `The page "null" cannot be found`

**Comment by bastianallgeier** [comment] 2018-11-09 16:01
Ha, I should have read your instructions more closely. I was actually able to reproduce the same issue in the file view of site files, but not in the site view itself. It's now fixed.

**Closed as completed by bastianallgeier** 2018-11-09 16:01 UTC
Labels: needs: information ❓
