### ISSUE TITLE
Toggle Field inside a structure field returns to old state after saving the page

### ISSUE THREAD

**Issue by nimi09** [getkirby/kirby#2669] opened 2020-07-01 10:17 UTC
**Describe the bug**  
A structure fields contains a field named "enabled" of type **toggle**. The List-View of the structure field displays also the toggle field and lets you "toggle" this field.
=> If you press the toggle field in the List-View and save the changes, the toggle field returns to the old state.

**To Reproduce**  
1. Go to a page which contains a structure field containing a toggle field
2. Click on the toggle option in the List-View
3. Click on save in the orange Save-Bar on the bottom of the page
4. After saving, the toggle in the List-View of the structure field returns to the old state

**Expected behavior**  
I expect that the toggle field stays in the now new and saved state after saving the page.

**Kirby Version**  
3.4.0.RC-1

**Console output**  

**Desktop (please complete the following information):**  
 - OS: 
 - Browser: 
 - Version:

**Comment by afbora** [comment] 2020-07-01 10:25
I can't reproduce the issue. Did you clear the caches?

![Toggle](https://user-images.githubusercontent.com/3393422/86233570-467c4e80-bb9e-11ea-90a4-b8a787e251d2.gif)

**Comment by nimi09** [comment] 2020-07-01 10:31
which caches? -> site/cache or browser chache?

**Comment by afbora** [comment] 2020-07-01 10:34
Browser cache but all if possible.

**Comment by nimi09** [comment] 2020-07-01 10:57
ok, downloaded the starter kit added kirby 3.4.0-rc.1 and it worked. But on my site i tried to delete all caches (kirby & browser) but the behavior still exits. Also if I try other browser such as firefox or safari.

However, the behavior changed to that extend that it works now on the first save action, but as soon as I save it a second time the error reoccurs.

**Comment by afbora** [comment] 2020-07-01 12:46
@nimi09 I tried with Firefox but i still can't reproduce.. Do you use any plugins or hooks? You can try without any plugins and hooks to debug the issue.

**Comment by nimi09** [comment] 2020-07-01 12:53
I use the editor plugin v1.0.2 ...

**Comment by nimi09** [comment] 2020-07-01 13:09
ok, found it, it's a Plugin issue. I use this color picker Plugin from TimOetting => https://github.com/TimOetting/kirby-color that causes the miss behavior.

**Comment by afbora** [comment] 2020-07-01 13:15
Good to find the source of issue. Closing the issue with pinging @TimOetting

**Closed as completed by afbora** 2020-07-01 13:15 UTC
Labels: needs: information ❓
