### ISSUE TITLE
Remote::get() triggers exception 60: unable to get local issuer certificate

### ISSUE THREAD

**Issue by foobartel** [getkirby/kirby#2752] opened 2020-07-30 02:44 UTC
**Describe the bug**  

I've been trying to get virtual pages set up with an API (following https://getkirby.com/docs/guide/virtual-pages/content-from-api), but get the following error, which seems to be triggered by `curl`: 

``
Exception (60)
SSL certificate problem: unable to get local issuer certificate
``

I've tried a lot of explanations on how to fix this, unfortunately to no avail.
I did have a look into the `Remote.php` class in the Kirby source and noticed that on line 188 it refers to `/cacert.pem`, which doesn't exist. If I change the `/cart.pem` location to where I know a .pem file exists, I get the same error that @georgobermayr describes in #2745.   

**Expected behavior**  
`Remote::get()` or `curl` should be able to run without errors. 

**Kirby Version**  
v3.4.0

**Desktop (please complete the following information):**  
 - OS: macOS 10.15.6 
 - Browser: Chrome or any
 - Version: any

**Environment**  
1. MAMP with trusted, self-signed SSL certificate
2. Apache on macOS with trusted, self-signed SSL certificate
Both setups run PHP 7.4

**Comment by lukasbestle** [comment] 2020-07-30 19:50
That's very weird. Unfortunately I cannot reproduce this on my Mac with Homebrew PHP or on my Linux server. :(

> I did have a look into the `Remote.php` class in the Kirby source and noticed that on line 188 it refers to `/cacert.pem`, which doesn't exist.

It refers to the `cacert.pem` file that we [ship with Kirby](https://github.com/getkirby/kirby/blob/3.4.0/cacert.pem). The file is located in the root of the `kirby` directory. Could you please verify again that this file does indeed not exist for you?

**Comment by foobartel** [comment] 2020-07-31 07:26
Thanks for checking and too bad you are not able to reproduce it on your setup. Regarding the `cacert.pem` in Kirby, it is indeed there and I actually didn't see it :( 

If I set `curlopt[CURLOPT_SSL_VERIFYPEER]` in `Remote.php` to `false` it works fine. That's not a real solution, but helps for now. 

I could share the API URL with you to try, even I don't think that this should be part of the problem, but I'm also not sure.
I'd be grateful for any further ideas…

**Comment by lukasbestle** [comment] 2020-07-31 09:00
Please see https://github.com/getkirby/kirby/issues/2745#issuecomment-666657398 for additional information. I have also linked a workaround to disable the verification in this post (although you are right – it‘s not a proper solution).

**Comment by foobartel** [comment] 2020-07-31 09:43
I tried the config options and with my API only `false` works, all others throw. 

Interestingly enough, with `Remote::get( 'https://getkirby.com/security.json' );`, both `Remote::CA_INTERNAL` and `Remote::CA_SYSTEM` work fine. It seems that the problem is rather with the API than on my Kirby side of things…

**Comment by lukasbestle** [comment] 2020-07-31 10:21
Ah, that is interesting! Can you tell me the API URL?

If you don‘t want to post it publicly, feel free to send an email to lukas at getkirby.

Thanks in advance!

**Comment by lukasbestle** [comment] 2020-08-03 18:16
Holger and I have been in contact via email and we have tried to debug and reproduce this error. Unfortunately we didn't find the issue and have therefore come to the conclusion that we'll close this issue for now until we have more information.

Possible workaround for using the pre-3.4.0 behavior just for one request that fails:

```php
Remote::get('...', ['ca' => false]);
```

To the reader: In case you are affected by this error as well, please let me know and I will reopen this issue to track this down.

**Closed as completed by lukasbestle** 2020-08-03 18:16 UTC
Labels: needs: information ❓
