### ISSUE TITLE
Cookbook recipe doesn't work anymore in 3.3.5

### ISSUE THREAD

**Issue by tristantbg** [getkirby/kirby#2527] opened 2020-03-17 17:49 UTC
**Describe the bug**  
The routing part of this tutorial doesn't work anymore in 3.3.5 but works in 3.3.4:
https://getkirby.com/docs/cookbook/templating/generating-json#using-your-json-representation__securing-your-json

**To Reproduce**  
1. Try to see the url with .json at the end.
2. It redirects to default page.

**Comment by afbora** [comment] 2020-03-17 18:17
I haven't tested with `HTTP_X_REQUESTED_WITH` but can't reproduce with direct access: `/blog.json`.
What happens when you try to access it directly from the browser without `HTTP_X_REQUESTED_WITH`?

**Comment by tristantbg** [comment] 2020-03-17 19:00
Even without the protection, the problem appears.

Here is a minimal boilerplate with the two kirbys at the root (just rename `kirby_3.3.4` or `kirby_3.3.5` to `kirby` to test the difference)
Then try to go to : `/index.json`

[routing-error.zip](https://github.com/getkirby/kirby/files/4345268/routing-error.zip)

Thanks !

**Comment by texnixe** [comment] 2020-03-17 20:48
Yes, I can reproduce this with your example. It works, if you add a template without the `json` extension. But that looks like a regression.

**Comment by texnixe** [comment] 2020-03-17 20:58
Maybe related to this? https://github.com/getkirby/kirby/issues/2471

**Comment by afbora** [comment] 2020-03-18 07:31
Yes, this is expected behavior. We've made an improvement to work more stable with the content representation about #2471 ticket that @texnixe mentioned. The file of the template (**/site/templates/index.php**) you want to represent must exist.

Btw we'd better add this information to the documents.

---

**Idea to improve a little more**

If there is no `index.json.php` file in the `index.json` request, `default.php` run. 
What would the order be like following? @lukasbestle 

**index.json request**

1. index.json.php
2. default.json.php (currently this work if there is no 3)
3. index.php
4. default.php (currently this work if there is no 1)

**Comment by texnixe** [comment] 2020-03-18 12:49
Ok, then the answer here would be: add a standard `index.php` template, or if you don't need the standard template for your HTML representation , return JSON from the standard `index.php` template. The behavior prior to 3.3.5 was inconsistent and therefore fixed.

**Comment by texnixe** [comment] 2020-03-18 13:03
@afbora I don't think your order is quite correct:

index.json request:

1. index.json.php
2. if index.php exists:  error page; if `index.php` does not exist: `default.json.php`
3. if `default.json.php` does not exist: error page

So if you want a `json` representation and there is no `json`representation, all you will ever get is the error page.

**Comment by afbora** [comment] 2020-03-18 13:05
@texnixe that was just the idea.

**Comment by texnixe** [comment] 2020-03-18 13:09
I think we can close this. As you can see I added an issue in the getkirby.com repo.

**Closed as completed** 2020-03-18 13:09 UTC
