### ISSUE TITLE
Blueprint Num `datetime` Gets Treated As `date`

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1424] opened 2019-01-30 23:47 UTC
**Describe the bug**
When using `num: datetime` in a Blueprint, it gets treated as `num: date`.

I suspect this line should look like `$format = 'date' == $mode ? 'Ymd' : 'YmdHi';`
https://github.com/getkirby/kirby/blob/4fef488a4a1b9644f8b89df227829fc1b6f9d108/src/Cms/PageActions.php#L383

**To Reproduce**
1. Create blueprint that specifies `num: datetime`
2. Make page visible

**Expected behavior**
Prefix should include time.

**Kirby Version**
`3.0.1-rc.1`

**Comment by neildaniels** [comment] 2019-02-02 00:14
If anyone needs a workaround to use `datetime`, the following works:
```
num: '{{ page.date.toDate("YmdHi") }}'
```

**Comment by bastianallgeier** [comment] 2019-02-02 12:37
This feels like a duplicate of https://github.com/getkirby/kirby/issues/1425

**Closed as completed by bastianallgeier** 2019-02-02 12:37 UTC

**Comment by bastianallgeier** [comment] 2019-02-02 20:10
✅ fixed on the develop branch
