### ISSUE TITLE
[3.5.0-rc.6] Date Field 12-hour time notation regression

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2991] opened 2020-12-10 23:42 UTC
**Describe the bug**  
The following Blueprint field shows a 12-hour notation time picker (with AM/PM) in Kirby 3.4.5.

```yaml
created:
  label: Published Date
  type: date
  translate: false
  time:
    step: 1
    notation: 12
  width: 1/3
```

In Kirby 3.5.0-rc.6, it shows a 24-hour time field.

**To Reproduce**  
1. Click into a date/time field with the above Blueprint field

**Expected behavior**  
The hour field should only go up to "12" and there should be a field for AM/PM.

**Screenshots**  
Kirby 3.5.0-rc.6:
<img width="330" alt="Screen Shot 2020-12-10 at 3 39 55 PM" src="https://user-images.githubusercontent.com/417182/101842993-22824900-3afe-11eb-9756-45341c998284.png">

Kirby 3.4.5:
<img width="319" alt="Screen Shot 2020-12-10 at 3 41 33 PM" src="https://user-images.githubusercontent.com/417182/101843052-3c239080-3afe-11eb-9f68-7667761bfe8b.png">

**Kirby Version**  
`3.5.0-rc.6`

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Safari 14.0.1 (16610.2.11.51.8)

**Comment by distantnative** [comment] 2020-12-12 10:03
Note to myself:
This was caused by not parsing the `time` option via the full time field. With doing so, this should be fixed.

Will be in the next RC and/or release.

**Closed as completed** 2020-12-13 11:04 UTC
