### ISSUE TITLE
checkboxes query string template language slug on structureobject fails

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#852] opened 2018-08-08 12:34 UTC
i am building a filter. storing titles in structure at $site. then querying the structure at other pages. i wanted to skip the part creating an additional url save version of the title (german umlaute, spaces etc) in another field. thus using the slug on title. but still using slug on title does not work. i do not want the id as value.

```
fetch: site.catmajor.toStructure
text: "{{ structureItem.title }}"
value: "{{ structureItem.title.slug }}" #fails
```

if i remember correctly the error displayed in panel was something like `field not found`.

**Comment by texnixe** [comment] 2018-08-08 12:36
Duplicate of #851

this is. not limited to structureItems

**Closed as completed** 2018-08-08 12:36 UTC
