### ISSUE TITLE
[Panel] Improve Required Files sections

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#616] opened 2018-07-10 10:07 UTC
1. All other required form-fields have a red-outline when content is missing on save.
2. All other required form-fields block save with validation-error ("Fix all form errors..")

**Comment by distantnative** [comment] 2018-07-11 07:36
Just to give a bit insight where this comes from: files is not a field but a section. You don't have a red outline around the whole fields section either.

**Comment by wottpal** [comment] 2018-07-11 08:58
Of course, I'm sometimes still thinking in v2 manner. But this might not be obvious for the panel-user, right?

**Comment by wottpal** [comment] 2018-07-11 13:49
I just thought about why blocking file-saving at all when there are form-errors in drafts? Because they can't be published with errors.

**Comment by wottpal** [comment] 2018-07-24 09:36
> I just thought about why blocking file-saving at all when there are form-errors in drafts? Because they can't be published with errors.

Any opinions on that? Should that be an extra issue?

**Comment by distantnative** [comment] 2018-08-24 09:12
I think this is actually a duplicate of https://github.com/k-next/kirby/issues/349 - I am closing this one here. If you would like to add anything to the other issue, please do there. This way we have all information in one place once we address this. Thanks.

**Closed as completed by distantnative** 2018-08-24 09:12 UTC
