### ISSUE TITLE
Creating the page `data` breaks the site

### ISSUE THREAD

**Issue by jenstornell** [getkirby/kirby#598] opened 2017-08-07 08:55 UTC
I tried to update an old site to the new Kirby 2.5.4 and it crashed. After some testing I found out that I can no longer have a page called `data`.

I have tested to add the folder `data` in the content root of a clean Kirby starterkit installation as well and I get the same problem there. I don't even need to add a text-file to that folder.

I get all kinds of warnings, but here are some:

>Notice: Undefined property: Children::$data in D:\xampp\htdocs\websites\kirby-2.5.4\kirby\vendor\getkirby\toolkit\lib\collection.php on line 545

>Warning: current() expects parameter 1 to be array, null given in D:\xampp\htdocs\websites\kirby-2.5.4\kirby\vendor\getkirby\toolkit\lib\i.php on line 63

**Comment by texnixe** [comment] 2017-08-07 10:37
What version is the "old site"?

**Comment by jenstornell** [comment] 2017-08-07 10:49
>What version is the "old site"? Kirby 1?

It's on 2.3.2, but it should not matter, because the issue appear on a fresh install of the starterkit as well.

**Steps to reproduce (with 2.5.4):**

1. Download starterkit.
1. Add the folder `data` into the `content` folder.
1. Go to the home of the website. It should crash.

**Comment by texnixe** [comment] 2017-08-07 10:50
I can reproduce the issue, but I also get it with Kirby 2.1, that's why I asked.

**Comment by lukasbestle** [comment] 2017-08-20 19:51
You still have time to guess where the issue was coming from.

Still waiting for you....

---

Turns out the issue was that collection filters unset non-matching items with `unset($collection->$key)` instead of `unset($collection->data[$key])`, which worked because of Kirby magic. But just not with items that have the key `data`.
The more you know. At least I had a good debugger that helped me finding this.

Anyway, fixed on the develop branch.

**Closed by lukasbestle** 2017-08-20 19:51 UTC
Labels: bug
