### ISSUE TITLE
Panel Date field with time displayed wrong

### ISSUE THREAD

**Issue by mauricerenck** [getkirby/kirby#1644] opened 2019-04-02 16:02 UTC
When setting a date and a time, using a date field in the panel, it seems like the timezone offset is added when saving. This offset is only shown, but not saved in the markdown.

**To Reproduce**
1. Use a date field in the panel, set time true
2. Select a date and set the time to 20:00
3. save
4. when in utc+2 the time will be shown as 22:00
5. In the markdown the time is still set to 20:00

**Expected behavior**
The displayed time won't change

**Screenshots**
![2019-04-02 17-54-13 2019-04-02 17_54_58](https://user-images.githubusercontent.com/964547/55417614-552a1f00-5571-11e9-90f0-e0f2197248e8.gif)

**Kirby Version**
3.1.1

**Comment by mauricerenck** [comment] 2019-04-02 16:22
Correction: I am now filling in data from 2005-11-xx and it jumps from 20:00 to 21:00 when saving.

**Comment by texnixe** [comment] 2019-04-02 17:48
Have you tested with 3.1.2-rc1 as well? It is supposed to be fixed and I can't reproduce your issue with that version. Closing this for now.

**Closed as completed** 2019-04-02 17:49 UTC

**Comment by alancwoo** [comment] 2019-10-31 01:19
Relating this issue in case https://github.com/getkirby/kirby/issues/1813
