### ISSUE TITLE
Site object not updated in a hook when `num: '{{ page.date.toDate("Ymd")}}'`

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#2581] opened 2020-04-18 12:01 UTC
**Describe the bug**  
When `num` is set to `'{{ page.date.toDate("Ymd")}}'` rather then just `date` in a page blueprint, and the status is changed from `draft` to `listed`, the site object in a hook is not updated when calling `site()->index()`.

Consider the following hook:

```php
'hooks' => [
    'page.changeStatus:after' => function () {
      $search = site()->index()->filterBy('template','*=','article');
      $search_results = [];
      foreach($search as $item) {!
          $search_results[] = [
              // Using relative paths not absolute
              'id'  => url::path($item->url()),
              'title' => $item->title()->value(),
              #'status' => $item->status()->value(),
          ];
      }
      // Write items to the file
      $json_data = json_encode($search_results, JSON_UNESCAPED_SLASHES);
      $fileoutput = kirby()->roots()->index() . '/' . 'search.json';
      f::write($fileoutput, $json_data);
  }
]
```
When numbering scheme is set to `num: date`, pages are correctly removed from the index when the status is changed to `draft` and added when the status is changed to `listed`.
Now if we change the numbering scheme to `num: {{ page.date.toDate("Ymd")}}`, pages are still correctly from the index when status is changed to draft, but no longer added when the status is changed from draft to listed.

The hook will work correctly both ways if we slightly change the code and call the `site()` on the new page object instead:

```php
   'page.changeStatus:after' => function ($newPage, $oldPage) {
          $search = $newPage->site()->index()->filterBy('template', '*=', 'article');
          $search_results = [];
          foreach($search as $item) {!
              $search_results[] = [
                  // Using relative paths not absolute
                  'id'  => Url::path($item->url()),
                  'title' => $item->title()->value(),
                  #'status' => $item->status()->value(),
              ];
          }
          // Write items to the file
          $json_data = json_encode($search_results, JSON_UNESCAPED_SLASHES);
          $fileoutput = kirby()->roots()->index() . '/' . 'search.json';
          F::write($fileoutput, $json_data);
      },
```
Is this intended behavior? And if so, why does the behavior depend on the setting of the numbering scheme?

**Kirby Version**  
3.3.5

Forum post:
https://forum.getkirby.com/t/changing-status-from-draft-to-listed-in-panel-does-not-seem-to-update-json-file-in-a-hook/17871/6

**Comment by lukasbestle** [comment] 2020-04-24 17:38
Related issue: #2555

**Comment by lukasbestle** [comment] 2020-04-24 17:39
In any case this is not expected behavior but a very 🤯 bug that is incredibly hard to debug unfortunately.

**Comment by afbora** [comment] 2020-09-01 08:59
I've tested and yes, the source of the issue is the same with #2555

**Comment by lukasbestle** [comment] 2020-09-19 15:59
I'm closing this issue to better keep the overview, see #2555.

**Closed as completed by lukasbestle** 2020-09-19 15:59 UTC
