### ISSUE TITLE
Remember active tab

### ISSUE THREAD

**Issue by H-i-red** [getkirby/kirby#1132] opened 2018-10-25 09:38 UTC
Remember which tab is active when navigate through the panel ? When you have a tab which contains “subpages” it would be nice to have it remember the “state” of the tab for quicker navigation through site.

**Comment by texnixe** [comment] 2018-10-25 09:39
Duplicate of https://github.com/k-next/kirby/issues/797

**Closed as completed by texnixe** 2018-10-25 09:39 UTC
