### ISSUE TITLE
Pages from the panel missing after enabling languages - because of certain letters in uploaded files

### ISSUE THREAD

**Issue by neropha** [getkirby/kirby#2445] opened 2020-02-12 17:06 UTC
Hi, 

this is my first bug report for Kirby 3. Great system so far, but I stumbled upon some weird behaviour, when enabling languages in an existing project. Some pages contain images uploaded through the panel and associated image.jpg.txt.

After enabling languages, only 2 out of 5 pages were displayed in the panel. I went through my content folders and renamed all _default.txt_ to _default.de.txt_ (de is my default language). Still no change.

I could open the pages in the Panel via URL though, but the former content seemed to be wiped out. When editing and saving that page, **not the _default.de.txt_ was changed, but one of the _image.jpg.txt_ files in the respective folder.** 

It happend with a file named istock-12346.jpg.txt first. I renamed file and TXT to _c.jpg.txt_ - **after that, the page appeared in the panel!** 

**Notice:** The meta-file didnt't have a language-suffix yet.

It looks, like this weird behaviour only occurs, when there jpg.txt-files with certain letters present. So far, i could determine following letters as "evil":

i,s,d,e,h,w,v,f,h,o,z

So a page-folder, that contains e.g. a z.jpg and a z.jpg.txt alongside, won't appear in the panel.

Apparently the problem was gone, after renaming all the meta-txts to have the default language suffix, but still I think this was a weird behaviour.

**Comment by afbora** [comment] 2020-02-12 18:09
@neropha I tried to do what you said, but I couldn't reproduce the issue in the 3.3.3 version. Can you write step by step if I ask? Like following:

**To Reproduce**  
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by distantnative** [comment] 2020-02-12 18:13
> After enabling languages

I think depending how exactly you did that could be very insightful.

**Comment by neildaniels** [comment] 2020-02-12 21:02
You need to rename your metafiles to resemble `filename.jpg.de.txt`. Notice how the language code is right before the `.txt` extension.

**Comment by distantnative** [comment] 2020-02-14 15:09
I will close this for now. I would assume that you added the languages manually and not via the Panel and missed to rename the files as pointed out by @neildaniels.

If not, please let us know and provide more information so we can look into it together. Thanks.

**Closed as completed by distantnative** 2020-02-14 15:09 UTC
Labels: needs: information ❓
