### ISSUE TITLE
[Panel] Allow simple templates in e.g. `label` and `help` too

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#796] opened 2018-08-02 06:55 UTC
For example:

```yaml
  jobs:
    type: fields
    fields:
      jobs:
        label: Stellenangebote in {{ page.title }}
        type: structure
        ...
```

**Comment by wottpal** [comment] 2018-08-02 06:56
Related https://github.com/k-next/kirby/issues/675

**Comment by distantnative** [comment] 2018-08-24 09:26
Duplicate of https://github.com/k-next/kirby/issues/600

**Closed as completed by distantnative** 2018-08-24 09:26 UTC
