### ISSUE TITLE
[Panel-UI] Tags-Field Icon Misplaced

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#260] opened 2018-03-20 14:02 UTC
Just a tiny ui hiccup when the tags-field is in the side-section:

<img width="331" alt="bildschirmfoto 2018-03-20 um 15 01 49" src="https://user-images.githubusercontent.com/3930150/37659204-a7661a5e-2c4f-11e8-9208-fb4388390f45.png">

**Comment by distantnative** [comment] 2018-03-20 21:17
Duplicate of https://github.com/k-next/starterkit/issues/129 – still thank you for reporting it! just closing this to keep a better overview.

**Closed as completed by distantnative** 2018-03-20 21:17 UTC
