### ISSUE TITLE
Crop bug when input image is too small

### ISSUE THREAD

**Issue by lemmon** [getkirby/kirby#3341] opened 2021-05-21 11:48 UTC
I have an image of dimensions 480 × 640. I am trying to crop it to

`$image->crop(280, 210)` -- OK
`$image->crop(560, 420)` -- output width is bigger then input image -- produces an image of dimensions 420 × 560 which is wrong, even orientation is invalid.

I am of opinion that it should produce image either:

a) crop to target dimensions within input image (480 × 360, in this case)
b) upscale the image

Preferably the "upscale" option would be ideal.

**Comment by lukasbestle** [comment] 2021-05-22 11:39
@afbora Could you please check why this happens?

**Comment by afbora** [comment] 2021-05-22 13:39
I couldn't reproduce the issue on Starterkit 3.5.5. When I want a larger output than the original, it gives me right. 

@lemmon Having the same issue with last Starterkit? 🤔

**Comment by afbora** [comment] 2021-05-22 13:46
Sounds like it was related/same to the #2695 issue @lukasbestle

**Comment by lemmon** [comment] 2021-05-26 08:27
@afbora Yes, it seems to be the case.

Image object dump:
```
[dimensions] => Array
        (
            [width] => 640
            [height] => 480
            [ratio] => 1.3333333333333
            [orientation] => landscape
        )

    [exif] => Array
        (
            [camera] => Array
                (
                    [make] => Apple
                    [model] => iPhone 11 Pro
                )
        )
```

It's actually a portrait image. Both browser and desktop are displaying it properly. Problem only occures when trying to crop above the original width.

**Comment by afbora** [comment] 2021-05-26 20:02
So closing this in favor of #2695

**Closed as completed by afbora** 2021-05-26 20:02 UTC
Labels: needs: information ❓
