### ISSUE TITLE
[Panel] Better differentiate unlisted/listed state icons

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#378] opened 2018-04-06 21:53 UTC
A small but important UI detail that I don't quite like in Alpha 8 is that the icons of unlisted/listed pages look quite similar esp. because they both have such a low opacity. I would give unlisted/listed icons full opacity and keep drafts as they are. This is also a nice visual hint for "These pages are visible/accesible" and these aren't.

<img width="511" alt="screen shot 2018-04-06 at 23 49 59" src="https://user-images.githubusercontent.com/3930150/38445875-9dec9918-39f5-11e8-8bae-3161f93cfc05.png">
 
Update: But maybe this also makes the user think the drafts-icon is disabled... :/

**Comment by REHvision** [comment] 2018-06-27 22:04
I guess I overlooked this issue and also suggested the same detail here #394

**Comment by distantnative** [comment] 2018-07-01 11:03
I'll close this as duplicate of other issues where this is covered too. Better to keep track of all issues. We already flipped the listed icon to differentiate them better.

**Closed as completed by distantnative** 2018-07-01 11:03 UTC
Labels: needs: discussion 🗣
