### ISSUE TITLE
Problem when filterBy  "kirby.user.id" in a blueprint

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#1941] opened 2019-07-22 13:43 UTC
I use the plugin “page display section” to select pages with a query.

It works and return pages if I hardcode the user id like this:
```page.drafts.filterBy('evaluatorId', 'kgesqYt', ',')```
"kgesqYt" is the current user id

but it does not return pages if I replace the harcoding id by "kirby.user.id"
```page.drafts.filterBy('evaluatorId', kirby.user.id, ',')```

The same query in a template works
```$page->Drafts()->filterBy('evaluatorId', $kirby->user()->id(), ',')```

Tested on Kirby 3.2.2

**Comment by bastianallgeier** [comment] 2019-07-31 09:09
@distantnative do you think your latest additions to the query parser could handle this at all or would @vauvarin need a custom collection for this case?

**Comment by distantnative** [comment] 2019-07-31 09:50
I’d think it could, but let me climb down to the refer hell first (in the next days).

**Comment by distantnative** [comment] 2019-07-31 16:57
I think the regex actually works fabulously 🎉
My current guess would be that this is caused by the plugin actually not providing `kirby` as data for the query: https://github.com/rasteiner/k3-pagesdisplay-section/blob/master/src/PagesDisplaySection.php#L21-L25

@vauvarin Does it work if you add `'kirby' => $this->kirby()` to the plugin?

**Comment by distantnative** [comment] 2019-08-23 09:25
Closing this for now. Please let me know if my suggestion does not work.

**Closed as completed by distantnative** 2019-08-23 09:25 UTC
Labels: needs: information ❓

**Comment by texnixe** [comment] 2019-10-05 18:39
Does this work for anyone? I tried this in a blueprint, to no avail:

```
query: site.find("notes").children.filterBy("userid", kirby.user.email)
```

Had to use this workaround to make it work:

```
query: site.find("notes").getUserPages()
````

And then in a page method or model, get the pages of the current user:

```
  'pageMethods' => [
        'getUserPages' => function() {
            return $this->children()->filterBy('userid', kirby()->user()->email(), '-');
        }
    ]
```
