### ISSUE TITLE
Panel UI get almost unusable increasing the number of fields

### ISSUE THREAD

**Issue by GernotBuettner** [getkirby/kirby#2736] opened 2020-07-23 12:18 UTC
---
name: Panel UI get almost unusable increasing the number of fields
about: Kirby panel text fields having typing delay with increase of fields amount.
---

**Describe the bug**  
With the increase of fields on a page in the Panel there is a visible delay when typing inside the input.
The delay increases with the typing speed and amount of fields on a page.

**To Reproduce**  
1. Download the page blueprint test.yml
2. create a page with the blueprint
3. start typing inside any of the text fields, increase the typing speed
4. increase or decrease the amount of textarea fields in the blueprint file to see the delay taking effect

**Expected behavior**  
Typing delay and overall interface responsiveness should not be affected by the amount of fields in the page.

**Screenshots**  
Performance capture during typing with the keydown event time visible.
![image](https://user-images.githubusercontent.com/22933536/88272054-67851a80-ccd8-11ea-9fd2-7ea9a5837f88.png)

CPU Workload of 8 cpu's during typing "lorem ipsum" in one field with 250 fields in the blueprint
![Untitled](https://user-images.githubusercontent.com/22933536/88271816-09f0ce00-ccd8-11ea-9193-b1ad6f39186a.png)

**Kirby Version**  
3.3.3

**Console output**  
Clean

**Desktop (please complete the following information):**  
 - OS: Fedora 30, PHP Version 7.1.30
 - Browser: Chrome Version 83.0.4103.116 (Offizieller Build) (64-Bit), Firefox Dev 79.0b9 (64-bit)
 
**Additional context**  
This is just a simplified test case, the same problem happens in real world scenarios using a mix of different field types.
You can verify the same problem replacing textarea with text fields, it is just a little bit less evident.
Issue happens on local test env and production server.
Test file: 
[test.zip](https://github.com/getkirby/getkirby.com/files/4965652/test.zip)

**Comment by bastianallgeier** [comment] 2020-07-24 08:09
Thanks for creating this extreme test scenario. It shows pretty clearly how our content store logic is way too heavy. I'm not yet 100% sure how we can fix this without removing the way that content changes are currently stored in localStorage, but we definitely need a fix for this.

**Comment by SkidX** [comment] 2020-07-24 08:59
Hi @bastianallgeier , thanks a lot for looking into it. 
I'm a @GernotBuettner colleague. Since this issue is creating us several problems (aka: clients complaining) and you said it should be related to storing values in the localStorage, I would like to ask you if maybe there is a temporary "quick & dirty" way to disable that localStorage feature until you come with a better solution, in order to have an acceptable user experience in the panel as soon as possible. I think most of our clients don't even realize that there is that feature, and certainly we never suggested them to rely on it to not loose data. 
What do you think, could it be possible?

Thanks again for your work

**Comment by GernotBuettner** [comment] 2020-07-24 09:12
Hallo @bastianallgeier ,
not much to add to @SkidX  comment, thank you for the quick response.

**Comment by afbora** [comment] 2020-07-28 10:11
I don't know very well, but I did a few tests, maybe it can give you an idea.

The reason it seems slow when typing fast seems to be caused by [Vue reactivity](https://vuejs.org/v2/guide/reactivity.html), not `localStorage`. When you remove following, you will see works great.

https://github.com/getkirby/kirby/blob/3.4.0/panel/src/store/modules/content.js#L196

I know following write is not correct, but I just wanted to see where slowness is. Likewise, if you write:

    state.models[id].changes[field] = value;

You will see that both wrote to `localStorage` and returned fast.

**Comment by bastianallgeier** [comment] 2020-07-28 10:15
@distantnative do you think we could fix this somehow by avoiding the costly reactivity part here?

**Comment by bastianallgeier** [comment] 2020-07-28 10:16
@afbora I didn't explain very well. It's not about storing changes in localStorage, but the comparison between old and new values on every input event.

**Comment by afbora** [comment] 2020-07-28 10:43
@bastianallgeier Understood. Is it possible to send store requests delayed? 

As an example of what I am trying to explain: https://vuejs-tips.github.io/v-debounce/

**Comment by distantnative** [comment] 2020-07-28 11:02
If it's technically possible, I'd have to check tonight.

The other option @afbora points to would be to only store changes on field blur, not on every keystone

**Comment by bastianallgeier** [comment] 2021-01-25 11:14
With 3.5.0, we finally fixed the underlying issue by debouncing the input event.

**Closed as completed by bastianallgeier** 2021-01-25 11:14 UTC

**Comment by GernotBuettner** [comment] 2021-01-25 14:16
@bastianallgeier Thanks for taking care of this topic.
