### ISSUE TITLE
[Panel] Cursor appears everywhere clicked on Edge browser

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2158] opened 2019-09-30 14:48 UTC
**Describe the bug**  

Wherever you click on the panel, the cursor/caret appears next to the element near where you clicked.

**To Reproduce**  
1. Go to panel on edge browser
2. Click anywhere close to elements
3. See issue

**Expected behavior**  
Cursor/caret should not appear if clicked place is not an input

**Screenshots**  
![edge2](https://user-images.githubusercontent.com/3393422/65889260-a04eae80-e3a9-11e9-8c0c-41e9080b71c6.gif)

**Kirby Version**  
3.2.5

**Console output**  
No output

**Desktop (please complete the following information):**  
 - Windows 10
 - Microsoft Edge 44.18362.329.0
 - Microsoft EdgeHTML 18.18362

**Comment by bastianallgeier** [comment] 2019-10-02 09:48
What a weird bug! I have absolutely no idea how this would even be possible.

**Comment by afbora** [comment] 2019-10-02 09:50
Don't get me wrong, I'm not the one who uses the Edge browser 😅 
I just noticed that when fixing with other bug.

**Comment by bastianallgeier** [comment] 2019-10-02 10:26
Hahaha, I wasn't blaming you for using Edge :) I actually thought that it's quite a decent browser. I just don't get where this bug could come from.

**Comment by lukasbestle** [comment] 2019-10-02 10:28
I had the same issue when testing another site in Edge. If I remember correctly, it was caused by opening Edge Dev Tools. Closing Dev Tools and reloading didn‘t even fix it, but opening a new tab did. So I think this is an Edge bug.

**Closed as completed by lukasbestle** 2019-10-02 10:28 UTC

**Comment by bastianallgeier** [comment] 2019-10-02 10:52
@lukasbestle LOL

**Comment by afbora** [comment] 2019-10-02 10:59
Since I didn't use Edge 😅, now i try to enter other sites when you told me. 
As you said, this error appears on all sites. Definitely the Edge bug. 
And you save my day ❤️

**Comment by nilshoerrmann** [comment] 2019-10-02 11:04
We also encountered this issue in another project and concluded this was an Edge bug.
Strange effect but only visible to the web developers.
