### ISSUE TITLE
[Cms] Use current $page if no path is passed to image() helper

### ISSUE THREAD

**Issue by isaactopo** [getkirby/kirby#1492] opened 2019-02-21 11:13 UTC
**Description**
The method image() when used with a path as a parameter is returning an error:
`Call to a member function url() on null`
When used with `$page->image('filename.jpg')` is working as expected

**Kirby Version**
"version": "3.0.2"

**Desktop Specs:**
 - OS: macOS 10.11.5
 - Browser: Chrome
 - Version: 72.0.3626.109

**Comment by texnixe** [comment] 2019-02-21 11:43
Do you mean the ` image()` helper method? It expects the path to the file, e.g.

```
<?php echo image('photography/animals/abba.jpg') ?>
```

**Comment by isaactopo** [comment] 2019-02-21 11:49
Yes, when used with `$page->image('filename.jpg')`is working as expected but when used solely as `image('filename.jpg)` throws the error: `Call to a member function url() on null`.

If I use `image()` without the filename parameter is working as expected too.

**Comment by texnixe** [comment] 2019-02-21 11:57
Come to think of it, yes, maybe it's a problem because the page helper should probably return the current page if the `$uri` is `null`.

Could be fixed by changing
https://github.com/getkirby/kirby/blob/69a948112af8380b9ff6fa0a6ab680136b97777e/config/helpers.php#L267

to

```
$page = $uri === '/' ? site() : $uri === null? page() : page($uri);
```

**Comment by isaactopo** [comment] 2019-02-21 12:24
Well, probably I'm not explaining well, on the docs https://getkirby.com/docs/reference/templates/helpers/image

The examples, does not work on my current Kirby installation. 

Here's a shot of the error:
<http://shared.topo.bz/Captura%20de%20pantalla%202019-02-21%20a%20las%2013.19.36-fcN0LaJiTJ.png>

Obviously “masaaki.jpg” is on `content/home`

**Comment by texnixe** [comment] 2019-02-21 12:56
Yes, as I pointed out above, I found that the problem is that the `image()` helper doesn't get the current page if `$uri` is null, and line #267 in the helper method has to be changed to make it work as expected.

Just on a side note, you shouldn't really call the `url()` method like you do without prior checking if you have an object, so no `$page->image('some image')->url()` or `image('someimage')->url()` but

```
($image = $page->image('some image'))? $image->url():null
```

**Comment by isaactopo** [comment] 2019-02-21 13:02
Thanks for your observation @texnixe , this code is only for explaining the situation, we always do a if statement to check if the image exists.

**Comment by bastianallgeier** [comment] 2019-03-27 14:34
✅

**Closed as completed by bastianallgeier** 2019-03-27 14:34 UTC
