### ISSUE TITLE
Smartypants settings not working

### ISSUE THREAD

**Issue by tweh** [getkirby/kirby#166] opened 2015-01-02 18:16 UTC
The configuration of smartypants seems to be ignored. For example I have `"Test"` in my text whits is pares with kirbytext and smartypants on to “Test”, so smartypants seems to work, but since it’s a german site I’d like to get „Test“ which I tried to achieve with

```
c::set('smartypants.doublequote.open', '„');
c::set('smartypants.doublequote.close', '“');
```

in `config.php` but the output is the same as without these options. You may reproduce this error with the starter kit adding some (wrong) quotes in the About text and add the options to the config file.

---

Seems to be connected to #76 of v1’s repo.

**Comment by bastianallgeier** [comment] 2015-01-14 10:49
After some more consideration I decided to put the config stuff for smartypants back in. Will be available in the next release.

**Comment by tweh** [comment] 2015-01-14 13:08
Sounds great but it would be great if [#317 from panel](https://github.com/getkirby/panel/issues/317) would be fixed together with this issue …

**Comment by frankrausch** [comment] 2016-11-21 19:00
The configurability of SmartyPants seems to be broken again in 2.4.0.

I have been able to reproduce the issue with a clean Starterkit and these lines in `config.php`:

    c::set('smartypants', true);
    c::set('smartypants.doublequote.open', '„');
    c::set('smartypants.doublequote.close', '“');

Instead of the German quotes it still shows the English ones.

**Comment by lukasbestle** [comment] 2016-12-19 14:06
I can confirm this. The Kirby [Smartypants component class](https://github.com/getkirby/kirby/blob/master/kirby/component/smartypants.php#L24-L40) has the defaults. And because the component is loaded lazily only when Kirbytext is run, those defaults override the options from config.php. We need to fix this in [kirby.php](https://github.com/getkirby/kirby/blob/2.4.1/kirby.php#L820) and make sure that existing options are not overwritten.

**Comment by fvsch** [comment] 2017-01-19 16:35
`Kirby::component` could loop on `$object->defaults()` and only add the keys not already found in `$this->options`. What's strange is I thought the order in the `array_merge` was already doing that. 🤔

**Comment by bastianallgeier** [comment] 2017-02-06 17:12
This is finally fixed by implementing the new Smartypants library version by Michael Fortin, which finally makes it much more straight forward to pass options instead of using nasty constants.

**Closed by bastianallgeier** 2017-02-06 17:12 UTC
Labels: bug
