### ISSUE TITLE
[Panel] Pagination errors

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2205] opened 2019-10-12 12:19 UTC
### Known Issues

**1. On files section upload**

> The section "files" could not be loaded: Pagination page 0 does not exist, expected 1-1

**To Reproduce**  
1. Go to panel
2. Edit any page
3. Upload to files section that empty

**2. Deleting/change status of item**

> The section "listed" could not be loaded: Pagination page 2 does not exist, expected 1-1

**To Reproduce**  
1. Go to panel
2. Delete or change status last remaing item on pages section of last page (pagination)
3. See error

**3. On pickers**

Will be fixed with current PRs.

**Kirby Version**  
Develop branch of 3.3.0

**Comment by lukasbestle** [comment] 2019-10-12 12:51
These are Panel issues, see #2182.

**Comment by afbora** [comment] 2019-10-12 12:51
@distantnative Please note that this fix is related to the panel ui.

**Comment by distantnative** [comment] 2019-10-12 13:21
Still needs to be fixed though? 🤨

**Comment by afbora** [comment] 2019-10-12 13:46
The bug has been fixed on the PHP side by @lukasbestle , but when the error is thrown on the panel, you cannot access the related field again even if refresh the page and logged out.

So when an error is thrown on panel side, we must ignore it or display the error without affecting the access the field/section.

**Comment by distantnative** [comment] 2019-10-12 13:51
I will try to fix them. For the future, I would prefer it if we only merge such changes when backend and Panel problems are fixed that are caused by these changes. Having them merged without dealing with the Panel makes it more difficult to stay on top of the changes and resulting bugs in my view.

**Comment by distantnative** [comment] 2019-10-12 13:54
If I read the code correctly the first error is not caused by the Panel but by line 406 of the new backend implementation - so I need your help to understand that @lukasbestle:

```php
        // allow a page value of 1 even if there are no pages;
        // otherwise the exception will get thrown for this pretty common case
        $min = $this->firstPage();
        $max = $this->pages();
        if ($this->page === 1 && $max === 0) {
            $this->page = 0;
        }
```

**Comment by lukasbestle** [comment] 2019-10-12 15:38
The issue is that the API and Panel have handled the pagination pages in a quite lax way before. It didn't cause any issues as the Pagination class silently ignored pagination pages that were out of bounds. Now that we validate that (which we need to do because of #1887), we suddenly see those bugs in the Panel implementation.

For some possible solutions, see my posts in #2182.

> For the future, I would prefer it if we only merge such changes when backend and Panel problems are fixed that are caused by these changes. Having them merged without dealing with the Panel makes it more difficult to stay on top of the changes and resulting bugs in my view.

In this case we only noticed the issues after the PR was merged. We didn't anticipate that there could be any issues with the validation as it only errors on invalid input. Basically we didn't anticipate that the Panel sometimes sends invalid input.

**Comment by distantnative** [comment] 2019-10-12 15:53
Understood.

But I think that one error is a bug in the backend where the page is set to `0` which immediately runs into the exception.

**Comment by lukasbestle** [comment] 2019-10-12 16:01
Are you referring to the first issue reported by @afbora?

I'd say that's a Panel issue as well. The empty section has `0` pages and will have `1` once something has been added to the section. The Panel should then request pagination page `1` as `0` is no longer valid. If the pagination page wasn't given at all in the API request, the API would automatically pick the first valid page, so it looks like page `0` is explicitly requested by the frontend code.

**Comment by bastianallgeier** [comment] 2019-10-14 11:05
For the frontend, the new validation is great and does exactly what it is supposed to do. 

But for the API I feel like it is making our lives and the lives of plugin developers a lot harder. We need to fix a lot more stupid pagination issues with additional requests or calculations like in @distantnative's PR. 

We have to keep in mind that there's a valid reason, why the error page should be shown when the pagination bounds are exceeded. It's better for SEO and also more clear for users. 

But in the context of the API, I pass a page parameter in the query and in this case it doesn't really matter if that page exists or not. The API should help with invalid page inputs and sanitize it to something useful – like before. This is exactly the reason why all paginated API requests return a pagination object with the actual details about the pagination. That's reference enough to find out if the input was valid or not. 

My suggestion would be to add a static $validate prop to the Pagination class, which can be used to toggle validation and exceptions. 

Something like

```php
Pagination::$validate = false
```

This could be used before each API request to ensure that we don't have the same Exception throwing behaviour there. 

What do you think?

**Comment by lukasbestle** [comment] 2019-10-14 20:23
I'm a bit split on this. On one hand I feel like this isn't as clean as it could be (as we will introduce global state with the static config property), but on the other hand I agree that it's a really simple and straightforward solution.

The best solution would be to catch the `ErrorPageException` in the API code that handles collection requests, but I imagine that this will be pretty hard to implement – the API code would then need to be clever and decide which page to use, which the Pagination class can do much better.

So you know what: Let's do it that way. See #2212.

**Comment by bastianallgeier** [comment] 2019-10-15 06:40
✅

**Closed as completed by bastianallgeier** 2019-10-15 06:40 UTC
