### ISSUE TITLE
Double slashes in page URLs when 'url' config has trailing slash

### ISSUE THREAD

**Issue by fvsch** [getkirby/kirby#564] opened 2017-03-13 19:22 UTC
Hi,

When the `'url'` option has a trailing slash, page URLs end up with double slashes. E.g.

```php
c::set('url', '/root/');

// [...]

echo kirby()->urls()->index(); /* "/root/" */
echo page('foo/bar')->url(); /* "/root//foo/bar" */
```

or:

```php
c::set('url', 'https://domain.org/');

// [...]

echo kirby()->urls()->index(); /* "https://domain.org/" */
echo page('foo/bar')->url(); /* "https://domain.org//foo/bar" */
```

Should Kirby maybe trim the URL before adding a slash before the page's (or parent page's) URI component?

Conversely, if the `'url'` config is expected to be without a trailing slash, I suggest making it clear on https://getkirby.com/docs/cheatsheet/options/url

**Comment by lukasleitsch** [comment] 2017-04-06 08:49
The issue is fixed in den develop branch. If the url has an trailing slash kirby will trim the url.

**Closed by lukasleitsch** 2017-04-06 08:49 UTC
Labels: bug
