### ISSUE TITLE
attribute required is broken for fields with type users

### ISSUE THREAD

**Issue by GiantCrocodile** [getkirby/kirby#1837] opened 2019-06-06 19:49 UTC
When I have this field:
```
  author:
    type: users
    required: true
```

I can save the page with no author selected. No error and validation happening.

Kirby 3.2.0 rc 2

**Comment by GiantCrocodile** [comment] 2019-06-06 20:01
Ah I found out what is wrong: The page can't be published because author is missing but there is no red error highlighting about the field due to its missing content. Other fields are highlighted properly if content is missing but required.

**Comment by distantnative** [comment] 2019-06-12 07:58
Duplicate of #1581

**Closed as completed by distantnative** 2019-06-12 07:58 UTC
