### ISSUE TITLE
[Panel] Improve Policy with Missing Required Files-Fields

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#633] opened 2018-07-11 14:04 UTC
With Kirby & files I often had one problem: I upload a file into a page and forget to fill in required fields of the file. But this is no problem for Kirby and I can even save the page. So why not either

- Disallow saving a page and display a form-error message like with required fields of the page itself or
- keep the current behavior but highlight the files with missing fields e.g. with a red outline

**Comment by distantnative** [comment] 2018-08-24 09:13
Duplicate of https://github.com/k-next/kirby/issues/349

**Closed as completed by distantnative** 2018-08-24 09:13 UTC
