### ISSUE TITLE
Duplicating a page in a multi language environment also copies untranslatable fields

### ISSUE THREAD

**Issue by manuelmoreale** [getkirby/kirby#2599] opened 2020-05-04 08:40 UTC
**Describe the bug**  
In a multi language environment, fields that are set to `translate: false` are getting copied when using the duplicate function within the panel. As a result, the new page will have data stored in both languages even though it should only have it in the default language.

**To Reproduce**  
1. Set up a multi language installation
2. Create a field and set the `translate` attribute to `false`
3. Fill that field in the panel in the default language
4. Duplicate the page
5. Check the txt files of the new cloned page.

**Expected behavior**  
The data of my field should only be present inside the default language txt file.
So for the sake of this example if my installation is in IT and EN with IT as my default language, the duplicated page should only have the value of my field stored in the `page.it.txt`.

**Comment by afbora** [comment] 2020-07-11 11:05
@manuelmoreale if I understand it correctly, i can't reproduce the issue. 
I have tested on 3.3.4, 3.3.6 and 3.4.0 and works great as expected.

Here my fields and duplicated page file content.  TR (Default Language) - EN

**note.yml**

````yaml
fields:
      test:
        type: text
        translate: false
````

**note.tr.txt**

````
Title: Evreni Keşfetmek

----

Test: Test TR

----

Text: Text TR

----
````

**note.en.txt**

````
Title: Exploring the universe

----

Text: Text EN

----
````

**Comment by texnixe** [comment] 2020-07-11 15:31
I can't reproduce this either in 3.4. The duplicated page does not contain the non-translatable field. @manuelmoreale, have you tested this in a fresh Starterkit without any custom code?

**Comment by bastianallgeier** [comment] 2020-07-13 08:16
@manuelmoreale I'm closing it. But feel free to reopen if you still run into the issue.

**Closed as completed by bastianallgeier** 2020-07-13 08:16 UTC
Labels: needs: information ❓

**Comment by manuelmoreale** [comment] 2020-07-13 10:29
So I can't replicate it now on latest version but there's definitely something going on with page creations in the context of languages and untranslatable fields. For example, if I create this blueprint right here

```
title  : Default Page
fields :

    textfield:
        label     : A Text Field
        type      : text
        translate : false
        default   : Default Content
```

And then I go in the panel, in the default language and I create a new page I get this draft

![Screenshot 2020-07-13 at 12 23 13](https://user-images.githubusercontent.com/1738077/87294164-a14d6880-c503-11ea-8598-dd4a813f033c.png)

But if i'm creating the same page while on the secondary language (de in this case) the new page gets created (only in .en. ) but the default text is not there

![Screenshot 2020-07-13 at 12 24 45](https://user-images.githubusercontent.com/1738077/87294308-d78ae800-c503-11ea-8baa-aa21df8d3fe0.png)

I'm gonna do a bit more testing on this one and see if I can find out which magic combination of fields i need to have in order to trigger that bug (if it's still there)

**Comment by lukasbestle** [comment] 2020-07-14 20:05
@manuelmoreale Once you are done with testing on this, please open a new issue for that problem. As this issue is closed, it will get lost here. :)
