### ISSUE TITLE
Pagination URLs have unnecessary query strings

### ISSUE THREAD

**Issue by wagnerpaul** [getkirby/kirby#1773] opened 2019-05-13 17:17 UTC
**Describe the bug**
The URLs returned by the pagination object's `nextPageURL()` and `prevPageURL()` seem to be getting spammed with query strings

**To Reproduce**
```php
<?php if($pagination->hasNextPage()): ?>
    <a href="<?= $pagination->nextPageUrl() ?>">
        next
    </a>
<?php endif ?>
```

**Expected behavior**
Expected URLs that look like `http://localhost/articles/page:3` instead get `http://localhost/articles/page:3?%2Farticles%2Fpage%3A2=&%2Farticles=`

**Kirby Version**
3.1.3

**Server:**
 - OS: nginx:1.14.0-alpine (docker)

**Desktop:**
 - OS: macOS
 - Browser: chrome
 - Version: 74.0.3729.131 (Official Build) (64-bit)

**Comment by lukasbestle** [comment] 2019-07-25 10:51
I cannot reproduce this, neither with Kirby 3.1.3 nor with 3.2.2.

What is the current URL in the browser address bar on the page where you get the strange next page URL? Please also post your options in `site/config/config.php`.

**Comment by bastianallgeier** [comment] 2019-07-30 10:26
I'm closing this because we can't reproduce it.

**Closed as completed by bastianallgeier** 2019-07-30 10:26 UTC
Labels: needs: information ❓
