### ISSUE TITLE
[Panel] New Page is created as `unlisted` and shows the wrong template

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#879] opened 2018-08-14 07:33 UTC
I have an issue with the latest nightly. Unfortunately I couldn't reproduce it with the Starterkit (even with my exact same blueprints 😕), maybe somebody has an idea: When I create a new page in a page-section defined like

```yml
  pages:
    status: all
    templates: filiale
    type: pages
```

the new page is (1) created as *unlisted*, (2) does not show up in the page-section but is created in `_drafts`, and (3) show the *default* template in the Panel instead of the defined one *filiale*.

I did not set up any languages if that helps.

**Comment by wottpal** [comment] 2018-08-14 07:42
I would happily zip up the whole site and send it to you privately. Just say me where :)

**Comment by bastianallgeier** [comment] 2018-08-14 10:46
@wottpal I think it would be good to get that zip. bastian@getkirby.com

**Comment by bastianallgeier** [comment] 2018-08-14 15:12
Works like a charm here. New Filialen are being created as drafts with the template filiale.txt as expected. I had to remove the kirby-git plugin though, to get it working at all without a repo.

**Comment by bastianallgeier** [comment] 2018-08-14 15:13
It's soooo cool to see a real-life example btw. <3

**Comment by bastianallgeier** [comment] 2018-08-14 15:15
I'm closing it for now. Feel free to reopen, if you can replicate it again.

**Comment by wottpal** [comment] 2018-08-14 19:12
> Works like a charm here. New Filialen are being created as drafts with the template filiale.txt as expected. I had to remove the kirby-git plugin though, to get it working at all without a repo.

Really? 😢 I've tested it once again on my development- and production-server and have the failure on both. I mean a `filiale.txt` is generated and it's in the `_drafts` folder like it should be but in the Panel a completely different template (`default`) is shown and it's not appearing in the pages-section...

**Comment by wottpal** [comment] 2018-08-14 19:14
![kapture 2018-08-14 at 21 14 27](https://user-images.githubusercontent.com/3930150/44113034-105f1468-a007-11e8-8059-855ef0f97aed.gif)

**Comment by bastianallgeier** [comment] 2018-08-15 09:51
Shit, I now know what the problem is. It's the page model. We have a PageDraft class for drafts, which of course doesn't work in this case, when there's a model. That means that the page is never really a draft, when it has a model. I have to find a work-around for this somehow.

**Comment by bastianallgeier** [comment] 2018-08-15 10:43
Fixed it! That actually helped to avoid a lot of future issues 👍

**Closed as completed by bastianallgeier** 2018-08-15 10:43 UTC

**Comment by wottpal** [comment] 2018-08-15 11:52
Glad you figured it out :)
