### ISSUE TITLE
[Regression] Permissions access 

### ISSUE THREAD

**Issue by vauvarin** [getkirby/kirby#3468] opened 2021-06-29 11:04 UTC
**Describe the bug**  
Permissions access set to false in a custom user blueprint did not disabled/faded corresponding items in the panel menu

**To Reproduce** 
Create a custom user blueprint
Set some access option to false 

 /blueprint/users/test.yml:

```
title: user test

permissions:
 access:
   panel: true
   site: true
   users: false
   settings: false
```

**Expected behavior**  
Items menu (users and settings in this example) should be disabled (not clickable) and faded.

**Kirby Version**  
3.5.6 and 3.5.7 rc1

**Desktop (please complete the following information):**  
 - OS: Linux
 - Browser: Firefox

**Comment by afbora** [comment] 2021-07-03 20:57
I've tested on [3.5.7](https://github.com/getkirby/kirby/releases/tag/3.5.7) and [3.6.0-alpha.1](https://github.com/getkirby/kirby/releases/tag/3.6.0-alpha.1). As your said, doesn't working in 3.5.6 and 3.5.7 (it's regression because of was working 3.4.x) but fixed in 3.6.0-alpha.1 ✅

**Closed as completed by afbora** 2021-07-03 20:57 UTC
