### ISSUE TITLE
User content is empty in multi-language setup

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2579] opened 2020-04-18 09:02 UTC
When a frontend user updates his content the file 

```
site/accounts/<user_id>/user.<languagecode>.txt
``` 

contains the fields, for example: `site/accounts/abcdef/user.en.txt`

the user has language `de` selected.

But when i - as a panel user - open the user's page, all the fields are empty. 

To my surprise, when i switch to `en` on the user's page in the panel, that makes no difference.
there is no way to see the content in the fields of that user at all. 

To reproduce:
- enable languages
- have a frontend user which edits and updates his content (`$user->update()`)
- check that the content is written to the user file
- see that there is none of user content visible in the panel (under no language at all), all fields are empty

**Comment by texnixe** [comment] 2020-04-18 14:15
@andreasotto I can't reproduce this in a 3.3.5 Starterkit. I did two things: manually updated the user content files to see if I can see the changes after refreshing the Panel and updating the user via template code.

Could you please post your code? Can you reproduce the issue in a fresh Starterkit?

**Comment by andreasotto** [comment] 2020-04-18 14:20
when using `$user->update()` in a controller do you have the content in both content files, when using two languages? i only got content in one content file, the other one contains not the updated content. 
As soon as the user switches his language, he is missing the other content, too. I used this to save a billing adress, which seems to be available only under one language now. 

As an admin in the panel all fields are empty for me and i don't get the content even with switching my language in the panel.

**Comment by texnixe** [comment] 2020-04-18 14:52
No, `$user->update()` only updates the current language. You can pass a second parameter along to tell Kirby which language you want to update. To update the other languages, you would have to call the method for all languages. For stuff like addresses I'd argue you might want to set the field to `translate: false` and only ever update the default language.

**Comment by andreasotto** [comment] 2020-04-18 16:23
I'll give that concept a try. Eventually thats something for the cookbook, and if i don't find another issue, we'd close this for now.

**Comment by lukasbestle** [comment] 2020-04-24 14:50
@andreasotto Did `translate: false` work for you?

**Comment by afbora** [comment] 2020-07-17 11:12
@andreasotto Does the issue still persist? Have you had a chance to try it with `translate: false`?

**Comment by afbora** [comment] 2020-07-27 18:49
I'm closing this for now. If the issue persists, feel free to reopen please 👍

**Closed as completed by afbora** 2020-07-27 18:49 UTC
Labels: needs: information ❓
