### ISSUE TITLE
[KirbyText] Horizontal rule is ignored below images

### ISSUE THREAD

**Issue by qwerdee** [getkirby/kirby#1482] opened 2019-02-14 13:27 UTC
**Describe the bug**
Adding a horizontal with `***` directly below an image requires two line breaks to be shown correctly. Not sure whether this is a bug or actually desired behavior. It worked like this in kirby 2 however so it breaks migrated content.

this doesn't work:
```
(image: an-image.jpg)
***

some text
```

this works:
```
(image: an-image.jpg)

***

some text
```

**Kirby Version**
3.0.1

**Comment by distantnative** [comment] 2019-03-16 09:15
This seems to be an issue in Parsedown.

Test case:
```php
public function testImageWithHr()
{
    $app = new App([
        'roots' => [
            'index' => '/dev/null'
        ]
    ]);

    $text = '(image: an-image.jpg)
***

some text';

    $expected = '<figure><img alt="" src="/an-image.jpg"></figure>
<hr />
<p>some text</p>';

    $this->assertEquals($expected, $app->kirbytext($text));
}
```

**Comment by lukasbestle** [comment] 2019-07-24 18:24
We confirmed that this is a bug in Parsedown, the Markdown library we are using. We have reported the issue at https://github.com/erusev/parsedown/issues/721. Closing this issue as we unfortunately can't fix it directly. Please upvote/comment on the issue over there, that would help a lot. :)

**Closed as completed by lukasbestle** 2019-07-24 18:24 UTC

**Comment by lukasbestle** [comment] 2019-07-25 10:13
This is intended behavior in the Markdown language according to https://github.com/erusev/parsedown/issues/721#issuecomment-514782612. That it worked with the older Parsedown version in Kirby 2 was a bug. It is recommended to always leave an empty line after KirbyTags.
