### ISSUE TITLE
[3.6.0-alpha.4] Page section "templates" option not working

### ISSUE THREAD

**Issue by pedroborges** [getkirby/kirby#3663] opened 2021-09-02 19:27 UTC
**Describe the bug**  

I have this page's section that works locally but not on the server:

```yml
headline: Projects
type: pages
empty: No projects yet
info: '{{ page.year }}'
limit: 20
parent: site.find('projects')
templates: project
```

This is what I see when clicking to add a new page on the server:

<img width="480" alt="Screen Shot 2021-09-02 at 16 28 37" src="https://user-images.githubusercontent.com/688309/131905355-fbf79865-78ad-4a77-9cac-f6abf4ea12a9.png">

This is the JSON returned when clicking to add a new page:

```json
{
    "$dialog": {
        "component": "k-form-dialog",
        "props": {
            "fields": {
                "parent": {
                    "type": "hidden"
                },
                "title": {
                    "label": "Title",
                    "type": "text",
                    "icon": "title",
                    "required": true,
                    "preselect": true
                },
                "slug": {
                    "label": "URL appendix",
                    "type": "slug",
                    "required": true,
                    "sync": "title",
                    "path": "/projects/"
                }
            },
            "submitButton": "Create draft",
            "value": {
                "parent": "/pages/projects",
                "slug": "",
                "template": null,
                "title": ""
            }
        },
        "code": 200,
        "path": "dialogs/pages/create",
        "referrer": "/pages/projects"
    }
}
```

After inspection, I figured it only worked locally because the `debug` option is enabled. Enabling it on the server fixes the issue. Is likely caused by [this check](https://github.com/getkirby/kirby/blob/cf6dd83e2ddc8eb458b8c21cd2e6f54d988be3c7/config/areas/site/dialogs.php#L276) but I couldn't figure what `option('debug') === true` is doing there.

I inspected the value of `$blueprints` and it's an array with 1 item both locally and on the server:

```
Array
(
    [0] => Array
        (
            [name] => project
            [title] => Project
        )

)
```

Now that I think about the content of `$blueprints`, it seems the check is wrong. A possible fix is:

```diff
- if (count($blueprints) > 1 || option('debug') === true) {
+ if (count($blueprints) > 0 || option('debug') === true) {
```

**Comment by texnixe** [comment] 2021-09-02 21:10
Duplicate of https://github.com/getkirby/kirby/issues/3644

**Closed as completed** 2021-09-02 21:11 UTC
