### ISSUE TITLE
[3.6.0] Modal appears in Panel: JSON response could not be parsed

### ISSUE THREAD

**Issue by foobartel** [getkirby/kirby#3508] opened 2021-07-09 04:41 UTC
**Describe the bug**  

A modal containing the complete panel opens and shows the a message of: "The JSON response could not be parsed:"

**To Reproduce**  
1. Open the panel
2. Wait a few seconds

**Expected behavior**  
Expected would be to not see this modal and not get an error. 

**Screenshots**  
![Screenshot 2021-07-09 at 12 31 03 PM](https://user-images.githubusercontent.com/1708876/125024207-e83c5280-e0b2-11eb-9295-bc925cab6a15.png)

**Kirby Version**  
3.6.0-alpha.1

**Console output**  
```
Uncaught (in promise) Error: The JSON response from the API could not be parsed
    at Object.onParserError (index.js:1)
    at X (index.js:1)
    at async Object.request (index.js:1)
    at async Object.go (index.js:1)
onParserError @ index.js:1
X @ index.js:1
async function (async)
go @ index.js:1
t.$go.window.panel.$go @ index.js:1
onClick @ index.js:1
Bt @ vendor.js:6
n @ vendor.js:6
Zr.i._wrapper @ vendor.js:6
```

**Desktop (please complete the following information):**  
 - OS: macOS 11.4
 - Browser: Chrome 
 - Version: 91

**Smartphone (please complete the following information):**  
 - Device: 
 - OS: 
 - Browser: 
 - Version: 

**Additional context**

**Comment by afbora** [comment] 2021-07-12 10:14
I couldn't reproduce the issue on Windows & Chrome.

**Comment by distantnative** [comment] 2021-07-17 16:58
Pretty sure this is a duplicate of https://github.com/getkirby/kirby/issues/3507 - since we are discussing over there, closing this one for now.

**Closed as completed by distantnative** 2021-07-17 16:58 UTC
