### ISSUE TITLE
Logging out user is not committed immediately

### ISSUE THREAD

**Issue by jpsjanne** [getkirby/kirby#2267] opened 2019-11-01 05:53 UTC
**Describe the bug**  
`Kirby()->user()` returns a `User` object even if `Kirby()->user()->logout()` has been called.

[Forum topic](https://forum.getkirby.com/t/user-logout-is-not-committed-immediately/16112/13)

**To Reproduce**  
1. Download and install starterkit-master
2. Create a new page template called “logout” and a corresponding content page: content/logout/logout.txt
3. Create an admin account in panel and log in
4. Enter the newly created logout page localhost/logout

Text **User is logged in** appears in an empty page, even though user is logged out. Any snippet or plugin used to render the page, which relies on `kirby()->user()`, thinks that the user is still logged in.

*site/controllers/logout.php*
```php
<?php

return function($site, $pages, $page) 
{
	$user = kirby()->user();

	if ($user) {
		$user->logout();
	}
};
```

*site/templates/logout.php*
```php
<?php
if (kirby()->user()) {
	echo 'User is logged in';
} else {
	echo "No user object";
}
?>
```

**Expected behavior**  

When entering *localhost/logout* and user is logged in, an empty page with text **No user object** should appear.

**Kirby Version**  
Tested that problem exists in version 3.2.5 and 3.3.0rc-4
Problem does **not** exist in version 3.1.4.

**Desktop (please complete the following information):**  
 - OS: Windows 10
 - Browser: Opera
 - Version: 63.0.3368.107
 - Server: XAMPP 7.3.7

**Comment by afbora** [comment] 2019-11-01 08:53
I can reproduce too:

````php
$user = kirby()->user('john@doe.com');
$user->loginPasswordless();
var_dump(kirby()->user());
$user->logout();
var_dump(kirby()->user()); // should be null but returns user data
````

The reason for this error is that the `kirby()->user()` method uses the `Auth` class to get current user, but the `$user->logout()` method doesn't use the `Auth` class, just clearing the session. 
Thus, the `$this->user` cached variable in the `Auth` class is still full, returning user data. 
On the other hand, the `auth()->logout()` method works correctly. Because this method also clears cache variables (`$this->impersonate = null; $this->user = null;`)

**Cms/Auth::logout()**
    
https://github.com/getkirby/kirby/blob/release/3.3.0/src/Cms/Auth.php#L339-L351

````php
public function logout(): bool
{
    // stop impersonating
    $this->impersonate = null;

    // logout the current user if it exists
    if ($user = $this->user()) {
        $user->logout();
    }

    $this->user = null;
    return true;
}
````

As a result, the logout method in the `User` class should also clear the user cached variables in the `Auth` class.

**Comment by lukasbestle** [comment] 2019-11-01 12:37
I agree that this is a bug.

Possible solution:

- Move the lines that unset the `$auth->impersonate` and `$auth->user` properties to a new `$auth->clearUser()` method
- Call that from the `$user->logout()` method with `$this->kirby()->auth()->clearUser()`

**Comment by distantnative** [comment] 2019-11-01 13:57
@lukasbestle thought: call it `flush` to be closer to terms already used in Kirby?

**Comment by lukasbestle** [comment] 2019-11-01 14:11
@distantnative Just `flush()` or `flushUser()`? I just saw that we'll also need a method to set the user, that would be `setUser()`.

**Comment by distantnative** [comment] 2019-11-01 14:57
@lukasbestle I think just `flush` could work - basically we are flushin everything that `Auth` is about - `impersonate` and `user` -, right?

**Comment by lukasbestle** [comment] 2019-11-01 15:37
@jpsjanne This bug is now fixed with https://github.com/getkirby/kirby/pull/2269. The fix will be in Kirby 3.3.1, but you can try it out already if you want. :)

**Comment by jpsjanne** [comment] 2019-11-01 17:07
Thanks everyone for the quick response! I'll just sit tight and wait for the update.

**Comment by bastianallgeier** [comment] 2019-11-18 10:45
✅

**Closed as completed by bastianallgeier** 2019-11-18 10:45 UTC
