### ISSUE TITLE
Files and Pages Panel fields fail on iOS

### ISSUE THREAD

**Issue by duncanmunro** [getkirby/kirby#3643] opened 2021-08-22 01:01 UTC
**Describe the bug**  

On iOS (I haven't any other phones to test with) Pages and Files fields will fail when trying to edit them in the panel on an iPhone. Clicking 'Add' in the Pages field or 'Add' then 'Select' in the Files field will result in a page reload rather than displaying the page/file picker.
I've tried Chrome and Safari, and using two different sites hosted on different servers. I initially had this issue on Kirby 3.5.6 then upgraded to 3.5.71 but the problem's still there. iOS is 14.7.1

(Chrome would occasionally throw up the sick folder icon and 'Can't open this page' though mostly just reload – couldn't see a pattern as to why)

I tried the forum for ideas first and got directed here as this seems similar to https://github.com/getkirby/kirby/issues/3077 (Replacing files fails on iOS 14 #3077)

**Comment by afbora** [comment] 2021-08-22 07:54
Same with #3183?

**Comment by distantnative** [comment] 2021-09-22 17:22
Based on the description I consider this a duplicate of  #3183

@duncanmunro if you have additional information that it's not the same issue, please let us know

**Closed as completed by distantnative** 2021-09-22 17:22 UTC
Labels: needs: information ❓
