### ISSUE TITLE
non-translated field doesnt change in translated page, when changed in original page

### ISSUE THREAD

**Issue by caplod** [getkirby/kirby#3222] opened 2021-03-23 14:25 UTC
** Kirby **
3.5.3.1

**Describe the bug**  
non-translated field doesnt change in translated page, when changed in original page.

**To Reproduce**  
1. Create a new page 
2. Change content in translated page
3. Change title in translated page
4. Change title in original page
5. Toggle boolean field in original page
6. Error: boolean field doesnt change in translated page

**Expected behavior**  
boolean field stays in sync

** Blueprint **

    title: Article
    preset: page
    fields:
      date:
        label: Date
        type:  date
        translate: false
        display: DD.MM.YYYY
        required: true
      showImages:
        label: Show image(s) on article page?
        type:  toggle
        translate: false
     ...

**Comment by afbora** [comment] 2021-03-23 15:36
Thanks for detailed report! This is known issue #2789 

Can you try following to confirm the issue is the same?
Use `show` as name of toggle field instead `showImages`. 
You will see that it has been saved correctly.

**Comment by caplod** [comment] 2021-03-23 16:07
yes, I can confirm that by renaming the field the error is gone.

**Comment by afbora** [comment] 2021-03-23 16:54
Closing this in favor of #2789

**Closed as completed by afbora** 2021-03-23 16:54 UTC
