### ISSUE TITLE
kirbytags:before and kirbytags:after Not Working

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#1266] opened 2018-12-14 00:00 UTC
**Describe the bug**
I cannot get the `kirbytags:before` or `kirbytags:after` hooks to be executed (neither from my config file nor from a plugin). 

**To Reproduce**
1. Add the following sample code to a `config.php` file
2. Display any page that has Kirbytext being used

```
return [
    'hooks' => [
        'kirbytags:before' => function ($text, $data, $options) {
            return 'TEST';
        },
    ],
];
```

**Expected behavior**
The outputted Kirbytext should be completely replaced with 'TEST'. However, the content remains exactly as it was.

**Kirby Version**
`3.0.0-beta-6.31`

**Additional context**
It seems like the code within the hook is never executed. You can stick an `echo` and `die()` in the block and it seems completely ignored.

**Comment by bastianallgeier** [comment] 2018-12-14 11:34
I'm sorry, but I have to close this. I cannot reproduce it.

**Closed as completed by bastianallgeier** 2018-12-14 11:34 UTC

**Comment by neildaniels** [comment] 2018-12-14 18:44
Yeah, narrowed the issue down to a bad plugin.
