### ISSUE TITLE
Improve login error handling

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2505] opened 2020-03-09 09:16 UTC
**Describe the bug**  
I tried to access the panel of a site I'm working on. The browser showed a grey page (the Kirby background grey). On reload, I saw an error message flashing before the page displayed grey again. After opening my developer tools, I finally got a login screen but after entering my details I got an "invalid login" error message:

<img width="817" alt="grafik" src="https://user-images.githubusercontent.com/25466/76198404-4ec70d00-61ee-11ea-8229-421792449247.png">

The console displayed:

```json
{
  "status": "error",
  "message": "Session \"1584443341.a59011126c27defd50ea\" is currently read-only because it was accessed via an old session token",
  "code": 400,
  "exception": "Kirby\\Exception\\LogicException",
  "key": "error.session.readonly",
  "file": "Session.php",
  "line": 524,
  "details": [],
  "route": "auth/login"
}
```

Deleting the session folder did not help. I could only login again after flushing my local storage.

**To Reproduce**  
Sorry, not sure, there was nothing special. I last visited the site before the weekend and now wanted to continue working. The login was set to be remembered.

**Expected behavior**  
If an invalid value in local storage is the culprit, I'd expect Kirby to clean that up for me automatically. In general, I'd expected a better error message that gives me a clue what happened because the given message suggested that I mistyped my credentials (which I did not).

**Kirby Version**  
3.3.4

**Comment by distantnative** [comment] 2020-03-09 09:23
@lukasbestle I get those errors quite a lot - but only when developing on Kirby and switching branches a lot (so I thought it might not be an issue). For me deleting the session files always worked. I have no understanding from the top of my head what's happening, but you might know if we could handle this smoother.

**Comment by nilshoerrmann** [comment] 2020-03-09 09:24
In our case, no branch switches were involved.

**Comment by nilshoerrmann** [comment] 2020-03-09 09:28
Ah, and this happened locally on macOS Catalina on Firefox 73.0.1 using Laravel Valet.

**Comment by lukasbestle** [comment] 2020-03-09 19:42
To explain where this error comes from: Sessions are regularly renewed for security. Each time a session is renewed, the session token (= the session cookie) changes and is retransmitted to the browser. So in normal operation the browser will have the new session cookie already for the next requests and will use that – which will work without issues. If the API still receives requests with the old token however, it will internally use the new session data for a limited time of 30 seconds, but in a read-only mode. If the API request tries to modify any data (like when trying to log in), the error is thrown.

The session token is also regenerated after every logout and login operation.  So it could be that you @nilshoerrmann logged out of the Panel and then tried to login again within 30 seconds. That normally works just fine, but in your case the HTTP response of the logout may have gotten lost, so your browser wasn't able to update its session cookie.

This error cannot occur after the session files have been deleted on the server though, because in this case the API won't be able to find the session from the session cookie (not even a read-only one) and will therefore automatically create an entirely new session.

@distantnative What you describe is strange as well: Branch changes shouldn't affect the `site/sessions` dir as those files are ignored by Git. So I can't really say where this could come from. It has never happened to me during development so far.

Regarding a possible fix: We could "fix" this by removing the read-only mode completely, which would mean that requests using the old session token would fail hard immediately and present a fresh login form. That would also reduce the complexity of the session implementation. However it would make parallel API requests unreliable. If multiple API requests are fired in parallel and one of them renews the session token, the later requests with the old token would fail or maybe even kick you out of the Panel.

**Comment by nilshoerrmann** [comment] 2020-03-09 20:27
> So it could be that you @nilshoerrmann logged out of the Panel and then tried to login again within 30 seconds. 

I did not actively. I looked more as if "some kind of error" might have caused it.

**Comment by distantnative** [comment] 2020-03-09 23:01
Actually, I think when developing it might be less the branch changing but more if I produce a rather harsh error.

**Comment by nilshoerrmann** [comment] 2020-03-10 10:13
The base problem is that there was an error that was not catched correctly, so my guess is there is a general problem here. And from what I see this is an issue of the panel.

The secondary issue is the one described here: because the initial error is not catched correctly the follow-up behaviour of making the session read-only is counterintuitive. So in the end, the user doesn't understand what happened and has no clue how to respond. But working on the session handling is not actually the right place.

The initial issue is an error that was not catched resulting in a cascade of subsequent faults, the session handling is the end of that cascade. Question is what was the initial error (I have no insights, sorry) and how can these kind of abstract error be catched more certainly?

**Comment by texnixe** [comment] 2020-03-10 17:34
I also get the `Invalid login` error every once in a while in my local environment but haven't really bothered to look closer because I thought I had messed things up somehow. It does not always help to delete the session files though, sometimes I just delete the user account.

**Comment by lukasbestle** [comment] 2020-03-10 19:16
As I said: This issue is probably caused by API responses that aren't delivered to the browser and therefore session cookies not being updated. That's a rare thing to happen, but it does happen from time to time (network issues, closing browser tabs/windows while a request is in progress etc.). There is unfortunately nothing we can do about it to fix it though. Not regenerating the session IDs at all would make the API and Panel insecure.

**Comment by distantnative** [comment] 2020-03-10 19:21
I don't have a deeper understanding of this, so I'm just gonna ask naive questions:
Shouldn't we still be able to act differently than to fail when the user tries to login again and we have checked that login and password are correct... instead locking the user out, we should throw away the old sessions, right?

**Comment by lukasbestle** [comment] 2020-03-10 19:45
Sorry, I don't really understand what you are referring to in the comparison (act differently than what)? Could you please rephrase that?

**Comment by distantnative** [comment] 2020-03-10 20:54
We have a current system that throws user out of the Panel and keeps them locked out (event if they try to log in with valid credentials), when some errors happen. And they seem to happen. That is bad.

Maybe we cannot avoid the throwing users out. But once a user tries to login again with valid credentials, we should ensure that works. Instead of throwing a very cryptic `... is currently read-only because it was accessed via an old session token` for users, the system should rather throw out all sessions for that user and create a new fresh one (since the user just provided valid credentials).

That's my train of thought without deeper knowledge.

**Comment by lukasbestle** [comment] 2020-03-11 20:47
Ah, I get it now. :)

I see two issues with this:

1. We can't assume that the sessions are only being used for Panel login. If we throw sessions away completely when they are in this read-only state, we also throw away other session information. Which wouldn't be a problem if it only happened in rare error conditions, but...
2. ...the read-only mode itself is a feature to make parallel API requests more reliable. If we'd throw away the session on the first request in read-only mode, that would be a race-condition:
    - The first request comes along and gets responded with a new regenerated session token.
    - Meanwhile the second request is sent with the old token (before the first response came back). This second request will be in read-only mode – which is fine if no writes are intended (as in normal Panel operation where the session won't ever need to be modified after login).
    - Now the third request comes along with the new session token. Everything is fine again and write access is possible again. But we would have deleted the session already now and the user would be kicked out of the Panel.

What we *could* do is to limit the automatic session deletion to cases where all of the following conditions are met at the same time:

- It's a `POST /api/auth/login` request,
- the exact `error.session.readonly` Exception was thrown *and*
- the session is completely empty (no data at all).

From my gut feeling I'm not sure though if that's a good idea. Looks like a hack to me.

**Comment by distantnative** [comment] 2020-03-15 10:03
On 1. + 2.: How about we handle it as current for a few seconds, but say if someone tries to login with the right credentials 10 seconds later, throw sessions away and let him?

**Comment by nilshoerrmann** [comment] 2020-03-15 11:49
If you do so please notify the user about that fact, e. g. something along the lines: “something is wrong, system will be locked for x seconds”.

**Comment by lukasbestle** [comment] 2020-03-19 21:04
The grace period (time the old session is still valid for) is 30 seconds at the moment, which is conservative to avoid issues in slow network setups (e.g. slow mobile data in a train in rural Germany 😝).

To be honest, I'm not sure if we need a fix for this – as all fixes will kind of be hacks. So far this only happened to you two. Maybe we should keep it in mind for now only and reconsider solutions when it occurs again. What do you think?

**Comment by nilshoerrmann** [comment] 2020-03-19 21:22
From a user point of view, Kirby's behaviour is still wrong: Kirby says my credentials were wrong which is not correct. That's completely broken UX in my eyes. The minimum is to provide a correct error message in my eyes.

> So far this only happened to you two.

Yes, but it's not a singular event. And what the user sees is misleading for anyone who will run into this issue.

**Comment by lukasbestle** [comment] 2020-03-29 19:36
> From a user point of view, Kirby's behaviour is still wrong: Kirby says my credentials were wrong which is not correct. That's completely broken UX in my eyes. The minimum is to provide a correct error message in my eyes.

You are right, the error message is indeed not good. It is [thrown here as catch-all for any login issues](https://github.com/getkirby/kirby/blob/3.3.5/panel/src/components/Forms/Login.vue#L78).

@distantnative Maybe we could differentiate between errors here:

- If the API returns the "Invalid email or password" error or any more specific auth error (with key `user.password.*`), the "Invalid login" message should be displayed.
- In all other cases, there should be an error message like "Error logging in. Please try again later.".

Another alternative: We could also always display the actual error message that comes back from the API instead of a generic one. I'd actually prefer that if possible.

**Comment by lukasbestle** [comment] 2020-11-13 20:55
@nilshoerrmann Does the read-only session still occur?

In any case, there's now a fix for the unhelpful "Invalid login" error message in #2926: If debugging is enabled, the actual error message will be displayed.

**Comment by nilshoerrmann** [comment] 2020-11-16 07:36
@lukasbestle No, I haven't encountered it lately.

> In any case, there's now a fix for the unhelpful "Invalid login" error message in #2926: If debugging is enabled, the actual error message will be displayed.

That's great 👍 Thank you!

**Closed as completed** 2020-11-16 10:49 UTC
