### ISSUE TITLE
[Panel] Inserting link in textarea makes panel jump to bottom of page

### ISSUE THREAD

**Issue by Pandorrrrrra** [getkirby/kirby#2271] opened 2019-11-02 12:13 UTC
**Describe the bug**  
Inserting a link in a textarea that contains a long text (so one has to scroll down the panel to see the end of the text) makes panel jump to the bottom of the page.

**To Reproduce**  
1. Create a textarea field
2. Go to the panel and insert a very long text.
3. At the beginning of the text insert a link via the link button of the texarea.
4. After clicking the "Insert" button of the modal see the panel jump down to the end of the textarea.

**Expected behavior**  
The panel should stay in the exact same position and not jump to the bottom of the page.

**Kirby Version**  
3.3.0-rc.4

**Desktop (please complete the following information):**  
 - OS: macOS Sierra 10.12.6
 - Browser: Firefox
 - Version: 70.0.1

**Comment by afbora** [comment] 2019-11-02 12:24
I can reproduce on 3.2.5 and 3.3.0 (Not tested older versions) with Firefox (Chrome working properly)

**Comment by afbora** [comment] 2020-07-27 18:45
@Pandorrrrrra I've fixed (tested on Chrome and Firefox) on #2744 and I'll be happy if you test with [dist.zip](https://github.com/getkirby/kirby/files/4983892/dist.zip)

**Comment by bastianallgeier** [comment] 2020-07-28 09:07
@afbora have you been able to reproduce this before your fix? I cannot reproduce the jump at all and I think the fix in your PR is not really doing anything. The submit event of the form is already prevented anyway. But maybe I'm missing something.

**Comment by afbora** [comment] 2020-07-28 09:11
@bastianallgeier Yes, I was having trouble with Firefox only too.

**Comment by afbora** [comment] 2020-07-28 09:27
@bastianallgeier Very interesting, I tested the issue last night on fresh 3.4.0 install, but today everything looks normal 🙈 Let me to some tests again.

**Comment by bastianallgeier** [comment] 2020-07-28 09:44
Phew, I'm glad you can't reproduce it either today. I tested this in 3 different browsers and haven't seen any jumping at all.

**Comment by afbora** [comment] 2020-07-28 09:57
I had to install older versions of Firefox. I reproduced on Firefox v70, v72 and i guess still continue on older versions. 

![2271](https://user-images.githubusercontent.com/3393422/88650857-caf4bb00-d0d1-11ea-9bde-e88533b20dfa.gif)

But works great on v78. I think this was a Firefox bug and it looks fixed on latest versions. I still don't understand why it wasn't working yesterday, sorry my fault 🙈

**Closed as completed** 2020-07-28 10:00 UTC

**Comment by bastianallgeier** [comment] 2020-07-28 10:12
Thanks for testing this so extensively!!
