### ISSUE TITLE
plugin cache without custom instance broken?

### ISSUE THREAD

**Issue by bnomei** [getkirby/kirby#1466] opened 2019-02-08 15:53 UTC
with kirby 3.0.1 issues are popping up for plugin caches not using custom instances being broken. is everything working as intended?

https://github.com/bnomei/kirby3-fingerprint/issues/6

https://forum.getkirby.com/t/custom-cache-in-plugin/12768/3?u=bnomei

**Comment by distantnative** [comment] 2019-03-06 13:37
@bvdputte provided the following small plugin to test:

```php
<?php

Kirby::plugin('superwoman/superplugin', [
    'options' => [
        'cache' => true
    ]
]);

$test = $kirby->cache("superwoman.superplugin");
var_dump($test);

$test->set("foo", "bar");
var_dump($test);
var_dump($test->get("foo"));
```

**Comment by bastianallgeier** [comment] 2019-03-11 14:09
Hm, I cannot reproduce this. Works fine for me. 

Feel free to reopen if it keeps on happening.

**Comment by bvdputte** [comment] 2019-03-12 10:47
@bastianallgeier I still can't get this to work, not even in a fresh starterkit (3.0.3).

This is the output:
```php
/var/www/test/kirby-starterkit.test/site/plugins/cachetest/index.php:10:
object(Kirby\Cache\Cache)[156]
  protected 'options' => 
    array (size=0)
      empty
/var/www/test/kirby-starterkit.test/site/plugins/cachetest/index.php:13:
object(Kirby\Cache\Cache)[156]
  protected 'options' => 
    array (size=0)
      empty
/var/www/test/kirby-starterkit.test/site/plugins/cachetest/index.php:14:null
```

**Comment by bvdputte** [comment] 2019-03-14 12:16
I investigated this a bit further and when I use 

```php
$test = $kirby->cache("superwoman.superplugin");
var_dump($test);

$test->set("foo", "bar");
var_dump($test);
var_dump($test->get("foo"));
```

in a template instead of in the plugin's `index.php` file, it seems to work.

So it's probably due to the fact that Kirby bootstrap isn't finished yet because it's still busy loading plugins?

**Comment by bvdputte** [comment] 2019-03-14 17:02
It works guys, it's my bad. You can safely close this issue.

Sorry 🙈

**Closed as completed** 2019-03-14 17:13 UTC
