### ISSUE TITLE
[Panel] Clicks in Safari Don't Always Work?

### ISSUE THREAD

**Issue by calebgrove** [getkirby/kirby#2619] opened 2020-05-15 04:18 UTC
**Describe the bug**  
Occasionally, clicking on action links in the Panel (+ Add, Save, Change URL, Change, Cancel, &c.) does nothing when using the latest release of Safari (13.1 on macOS Catalina 10.15.4). Nothing is logged to the browsers console. Upon repeatedly clicking the link (anywhere from two to twenty times), the action will work as it should.

This bug appears to only be in Safari. Chrome and FF work as expected. Tested with a fresh starterkit install.

**To Reproduce**  
Click on a panel link. It's not 100% reproducible every time, I would say that the error occurs about 50%-75% of the time.

**Screenshots**  
Screen recording: https://files.grovedesign.co/kirby-panel-bug-1589515955/kirby-panel-bug.mov

**Kirby Version**  
Kirby 3.3.6
Fresh starterkit with no modifications or plugins.

**Console output**  
Nothing.

**Desktop (please complete the following information):**  
 - macOS 10.15.4
 - Browser: Safari (This bug appears to only be in Safari. Chrome and FF work as expected.)
 - Version: Version 13.1 (15609.1.20.111.8)

**Comment by calebgrove** [comment] 2020-05-15 04:25
I just realized that I should probably test in Safari Tech Preview (Release 105 [Safari 13.2, WebKit 15610.1.10]). I'm happy to report that this bug is not present in that version.

Which would lead me to believe that this is just a Safari 13.1 bug. I'll leave this issue open for now; but feel free to close.

**Comment by lukasbestle** [comment] 2020-05-15 19:59
I have tested this with the exact same Safari version you have (15609.1.20.111.8), but can't reproduce it. Safari is actually the browser I use daily for development and I have never seen this behavior before.

So maybe this is happening because of browser extensions or configuration?

I'm closing this issue for now. If this issue occurs again, please let us know and we will reopen the issue.

**Closed as completed by lukasbestle** 2020-05-15 19:59 UTC

**Comment by calebgrove** [comment] 2020-05-15 23:47
Well, I disabled all extensions and it didn't fix it. However, it sounds like it's a problem with my environment, so... ¯\_(ツ)_/¯

Regardless, thanks!
