### ISSUE TITLE
Is character number limited in kirbytext tags ?

### ISSUE THREAD

**Issue by Ventricule** [getkirby/kirby#238] opened 2015-04-17 10:07 UTC
Hello,
It appear that when I use *italic* or **bold** tags in kirbytext area, when the content between tags is larger than ~375 character, it broke : the page containing the text dont load at all.
Do you have the same problem ? An idea of the problem origin ? for me its a bit curious.

**Comment by distantnative** [comment] 2015-05-05 07:36
Is that problem still existent for you with the current 2.1 beta (from the develop branch)?

**Comment by bastianallgeier** [comment] 2015-08-27 13:06
I can't reproduce this and since there's no answer I'm closing it.

**Closed by bastianallgeier** 2015-08-27 13:06 UTC

**Comment by nils-werner** [comment] 2015-11-12 16:21
We have the exact same issue, but with 624-625 characters between `*...*`.

We are seeing this on a machine 

 - Windows
 - PHP 5.6.14
 - `memory_limit = 2G`
 - `pcre.backtrack_limit = 1000000`
 - pcre.recursion_limit = 100000`

**Comment by bastianallgeier** [comment] 2015-11-12 16:25
Could you repost this issue on the Parsedown repository? https://github.com/erusev/parsedown/issues I still can't reproduce it on my machine even with more characters. But when there is such an issue on Windows or with different server specs, it's something the Parsedown folks should have a closer look at.

**Comment by nils-werner** [comment] 2015-11-12 16:27
Just fyi: I see segfaults on my Mac with more than 15834 characters.

**Comment by bastianallgeier** [comment] 2015-11-12 16:33
Ok, I can reproduce it now as well with such a high number of characters. I wonder if they can do anything about it at all.
