### ISSUE TITLE
Structure field methods not working on custom user fields

### ISSUE THREAD

**Issue by texnixe** [getkirby/kirby#336] opened 2015-12-05 10:43 UTC
Probably related to #333; 

Use of `yaml()` or `toStructure` methods on user structure fields throw fatal error: 
> Fatal error: Call to a member function yaml() on string

**Comment by afbora** [comment] 2015-12-05 10:44
Yes same issue. Methods not working on custom user fields.

**Comment by bastianallgeier** [comment] 2015-12-05 14:09
I'm closing this. It's a duplicate.

**Closed by bastianallgeier** 2015-12-05 14:09 UTC

**Comment by CelineDesign** [comment] 2016-02-11 10:47
@bastianallgeier  you marked this issue as a duplicate of #333, then mark #333 as an enhancement.
I'm ok that field method on user field, is an enhancement and not an issue, because there's workarounds for that (see #333).

But be careful that this issue, is not an enhancement but a real bug : 
At the moment, we can't use structure in user blueprint !
The saved yams in user is not valid (i think there's some indentation issue), and thus unreadable.

So, i think this issue should NOT be marked as a duplicate of #333, and solved ASAP.

Thanks.

**Comment by lukasbestle** [comment] 2016-02-11 13:54
The issue you are referring to is another issue and unrelated to the missing field methods. See getkirby/panel#703.
