### ISSUE TITLE
Panel install not working although Apache is running

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#460] opened 2018-05-16 08:56 UTC
The Panel in Alpha 10 throws an error, that Apache, Nginx or Caddy are required, although I have Apache running (Ubuntu 17.10).

Apache works with all my other localhost projects so what's the issue that Kirby 3 runs into or what does it expect me to do in order to make it work?

![bildschirmfoto von 2018-05-16 10-40-21](https://user-images.githubusercontent.com/2584674/40106476-31bcf2fe-58f6-11e8-8549-1b7d68841d8f.png)

**Comment by bastianallgeier** [comment] 2018-06-18 20:13
Sorry for the delay, but would you be able to create a simple test.php somewhere on your server and send me the output of this: 

```php
<?php var_dump($_SERVER['SERVER_SOFTWARE']);
```

We use that to detect the server software. It might be possible that yours is simply hidden.

**Comment by REHvision** [comment] 2018-06-19 00:15
No worries ;)
Actually, I never tried it on the server before (I wanted to test it on localhost of course)...
Now that I did, the panel install works like a charm on the server. So I can play with it there but I would still prefer to have it running on localhost, too.

**localhost:**
`string(59) "PHP 7.2.5-1+ubuntu17.10.1+deb.sury.org+1 Development Server"`

**server:**
`string(21) "Apache/2.4.6 (CentOS)" `

**Comment by bastianallgeier** [comment] 2018-06-19 08:33
Looks like you are running PHP's built in server on your machine. That is actually not really Apache and we have some compatibility issues atm because of its weird routing logic.

**Comment by REHvision** [comment] 2018-06-20 20:50
I see, thank you for the infos and I hope you can fix this for the release :wink: Otherwise just document the supported and problematic server configurations :smile:

**Comment by bastianallgeier** [comment] 2018-06-25 11:36
I will close this issue, because it's a duplicate of this: https://github.com/k-next/starterkit/issues/43

**Closed as completed by bastianallgeier** 2018-06-25 11:36 UTC
Labels: needs: information ❓
