### ISSUE TITLE
Updating page unsets all global variables in snippets

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#2737] opened 2020-07-23 18:16 UTC
**Describe the bug**  
When I update the current page inside a controller and the current page is sorted by date, all global variables are unset inside snippets. They are still available in templates, but no longer in snippets.

**To Reproduce**  
Take the current Starterkit:
1. Go to the `note.yml` blueprint and change `num: date` to `num: '{{ page.date.toDate("Ymd") }}'`
2. Create a controller `note.php`:
```php
<?php

return function ($page) {
    $page->update();
};
```
3. Visit `/notes/exploring-the-univers`.
4. See error.

**Expected behavior**  
Updating the current page should not interfer with variable availability in snippets.

**Screenshots**  
<img width="1676" alt="Bildschirmfoto 2020-07-23 um 19 16 13" src="https://user-images.githubusercontent.com/25466/88322536-249b6500-cd21-11ea-938b-96eaaf5e4025.png">

**Kirby Version**  
Kirby 3.4 – I haven't tested in prior versions yet.
This is a single language install.

**Additional context**  
Forum discussion: https://forum.getkirby.com/t/updating-page-content-in-a-controller/

**Note**
In the context of the Starterkit, it's not required to use the query syntax to sort by date but in my install there is no date field named date. So this cannot be solved by switching to `num: date`.

**Comment by nilshoerrmann** [comment] 2020-07-23 18:18
The referenced forum post gives more insight on the original context. This is a broken down version of the problem.

**Comment by afbora** [comment] 2020-07-23 18:36
I've tested on 3.3.6 and reproduced the issue in that. 

Also error dissapear when you remove the `->clone()` call from following line:

https://github.com/getkirby/kirby/blob/3.4.0/src/Cms/PageActions.php#L539

**Comment by nilshoerrmann** [comment] 2020-07-23 18:47
Now that I think about the issue of vanishing variables, a few weeks ago I noticed a missing variable in a snippet that I thought worked the other day. I've got two blueprints with date-based sorting, all other pages are sorted differently. So it might have been the same situation where the snippet worked for normally sorted pages but not for the date-based ones. 

I did not update any pages programatically at that time – so this issue might also arise in other situations.

**Comment by distantnative** [comment] 2020-07-23 20:17
@afbora we have to be careful here. Cloning was added so we can set the object to the default language (which we need for proper date num calculations). If we just remove it, I’d assume we break non-default languages in multi languages setups cause that code part would change the language for the actual app instance

**Comment by afbora** [comment] 2020-07-23 20:20
@distantnative The incident is under control, this is just a small trace 😅

**Comment by nilshoerrmann** [comment] 2020-07-24 09:07
Anything I can do as an intermediate fix?

**Comment by afbora** [comment] 2020-07-24 11:02
@nilshoerrmann Is multi-language enabled on the site where you got the error?

**Comment by nilshoerrmann** [comment] 2020-07-24 11:09
No, it isn't.

**Comment by afbora** [comment] 2020-07-24 11:15
Then you can remove kirby's clone method as a workaround on line:

https://github.com/getkirby/kirby/blob/3.4.0/src/Cms/PageActions.php#L539

````php
$app = $this->kirby();
````

No cloning is required for instance to get with default language because multi-language is not enabled. It is always the default language.

**Comment by nilshoerrmann** [comment] 2020-07-24 11:16
Thanks!

**Comment by lukasbestle** [comment] 2020-07-26 14:22
We have another issue for this here: #2555
I'm closing this so we can better keep an overview.

**Closed as completed by lukasbestle** 2020-07-26 14:22 UTC
