### ISSUE TITLE
[Panel] Internal links are broken

### ISSUE THREAD

**Issue by nilshoerrmann** [getkirby/kirby#497] opened 2018-06-12 08:51 UTC
All links inside the panel ignore the panel's path and route to the site's root directly:

```html
<a href="/pages/projects+title" class="kirby-link kirby-list-item-content">…</a>
```

This works as long as you stay in one window because of some JavaScript routing magic I guess, but opening a link in a new tab or window results in broken links: `https://example.com/pages/projects+title` instead of `https://example.com/panel/pages/projects+title` or even `https://example.com/my/path/to/the/panel/pages/projects+title`.

**Comment by lukasbestle** [comment] 2018-06-12 13:39
Duplicate of #464.

**Closed as completed by lukasbestle** 2018-06-12 13:39 UTC
