### ISSUE TITLE
Range field tooltip overlapping when the width is narrow on Firefox

### ISSUE THREAD

**Issue by HYR** [getkirby/kirby#2961] opened 2020-11-30 13:32 UTC
When setting the range field width to `1/3` and using an `after:` value, the tooltip overlaps the `after:` value.

![image](https://user-images.githubusercontent.com/5200901/100615956-9db15700-32d5-11eb-814a-63edd0d96812.png)

![image](https://user-images.githubusercontent.com/5200901/100616041-bd487f80-32d5-11eb-9830-47389ee44f38.png)

**Comment by afbora** [comment] 2020-12-01 19:06
I have test blocks and layout field on 3.5.0-RC.2 and couldn't reproduce the issue with before and after option both.

![screen-capture-510-Sandbox - Mægazine-localhost](https://user-images.githubusercontent.com/3393422/100785055-2be62400-3421-11eb-838c-c9340d34147f.png)

````yaml
fields:
  blocks:
    type: blocks
    fieldsets:
      test:
        name: Range
        icon: bolt
        fields:
          range1:
            label: Range 1
            type: range
            min: 1
            max: 10
            after: px
            width: 1/3
          range2:
            label: Range 2
            type: range
            min: 1
            max: 10
            before: width
            width: 1/3
          range3:
            label: Range 3
            type: range
            min: 1
            max: 10
            before: width
            after: px
            width: 1/3
````

**Comment by afbora** [comment] 2020-12-01 19:11
If the issue persists, there may be a problem with the OS or browser. Can you share operating system and browser details?

**Comment by HYR** [comment] 2020-12-01 22:24
This is on Firefox 83.0:
![image](https://user-images.githubusercontent.com/5200901/100803875-28cf4180-33e9-11eb-8fef-a1591ee79b18.png)

MacOS 10.15.3

**Comment by HYR** [comment] 2020-12-01 22:27
This is part of a custom block blueprint if that makes any difference. 🤷‍♂️

**Comment by afbora** [comment] 2020-12-02 08:31
The issue was caused by Firefox. Looks perfect on Chrome. But this has nothing to do with the blocks/layout field and Kirby 3.5.x. The issue arises when the width narrow (`width: 1/3` and `width: 1/4`) even on the normal page for Firefox and Kirby 3.4.x

![image](https://user-images.githubusercontent.com/3393422/100847663-258f9080-3491-11eb-9357-aa909a26c616.png)

**Comment by afbora** [comment] 2021-10-01 23:02
I've tested with Firefox 91 and Chrome 94 on 3.6.0-beta.2, seems fixed 🎉 @HYR Can you confirm too?

**Comment by distantnative** [comment] 2021-12-22 14:28
I assume this has been fixed via the newer Firefox release. @HYR if it still exists for you, please let us know.

**Closed as completed by distantnative** 2021-12-22 14:28 UTC
