### ISSUE TITLE
User role method and translations conflict

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#1966] opened 2019-08-01 14:35 UTC
**Describe the bug**
I don't know how, but there's a conflict between the user role and the translations. I couldn't make the connection. I have to explain by giving an example:

**Sample**

**/site/plugins/your-plugin/index.php**

```
<?php

Kirby::plugin('your/plugin', [
    'translations' => [
        'en' => [
            'export' => 'Export',
        ],
        'de' => [
            'export' => 'Exportieren',
        ]
    ]
]);
```

**/site/controllers/home.php**

```
<?php

return function ($page) {
    echo t("export", "Hello World!");
};

```

**Output**: `Export`

Everything OK!
Now let's uncover the error:

**To Reproduce**

1. Login
2. Use following codes

**/site/plugins/your-plugin/index.php**

```
<?php

$role = kirby()->user()->role(); // This line conflict with only role() method

Kirby::plugin('your/plugin', [
    'translations' => [
        'en' => [
            'export' => 'Export',
        ],
        'de' => [
            'export' => 'Exportieren',
        ]
    ]
]);
```

**Output**: `Hello World!`

**Important note that issue only called `role()` method, tried other methods worked like id(), name(), email() etc..**

For example following codes works with `kirby()->user()`

```
<?php

$user = kirby()->user();

Kirby::plugin('your/plugin', [
    'translations' => [
        'en' => [
            'export' => 'Export',
        ],
        'de' => [
            'export' => 'Exportieren',
        ]
    ]
]);
```

**Kirby Version**
3.2.3-RC.1

**Comment by lukasbestle** [comment] 2019-08-04 11:57
It looks like this issue only occurs because you access Kirby objects from your plugin's `index.php`. As always, this is an edge-case and cannot always be fully supported. We may take a look if we can track this issue down when we find the time, but unfortunately it's a lot of effort to do that compared to the effect given the edge-casyness.

**Comment by afbora** [comment] 2019-08-04 12:07
In fact, we have this issue when accessing only one method as `role()`, not when we get to the object.

I will track the source of the issue and report it to you.

**Comment by afbora** [comment] 2019-08-04 13:51
I found the reason why the translations inside the plugin did not load.

[I18n::translate()](https://github.com/getkirby/kirby/blob/master/src/Toolkit/I18n.php#L110) method in Role class (/cms/Role.php) run before the plugins  and `$translations` variable set here so prevents to load translations of plugins.

Here the process steps when the `role()` method called logged as admin role:

1. kirby()->user()->role()
2. [Users::role()](https://github.com/getkirby/kirby/blob/master/src/Cms/Users.php#L128)
3. [Role::admin()](https://github.com/getkirby/kirby/blob/master/src/Cms/Role.php#L47)
4. [Role::defaults()](https://github.com/getkirby/kirby/blob/master/src/Cms/Role.php#L56)

`I18n::translate()` method called 6 times in role class and when I removed `I18n :: translate()` methods in `Role` class, plugin translations works properly.

I understand it's pre-load, but it doesn't make sense to not be able to access any kirby objects like session, user, etc from within the plugin.

Similiar issue: https://github.com/getkirby/kirby/issues/1892#issuecomment-516403797

**Comment by lukasbestle** [comment] 2019-08-04 14:36
Thanks for the additional info.

I understand that issues like this aren't great to deal with and are often unexpected, but unfortunately the problem is always that we can't fix those issues without changing the loading order. And that will break other Kirby features.

Getting any Kirby object from plugins' `index.php` files or the Kirby config is just not supported and can never be. The workaround is to postpone those calls to a later point, e.g. with the upcoming plugins loaded hook (https://github.com/getkirby/ideas/issues/23). If that won't help for your plugin for any reason, feel free to open an idea issue with your suggestions.

I'm closing this issue as we can't fix it without breaking the loading order.

**Closed as completed by lukasbestle** 2019-08-04 14:36 UTC

**Comment by afbora** [comment] 2019-08-05 08:23
They all come up with this idea as ideas#23. Hopefully it will be released as soon as possible.

I solved the problem by resetting the `$translations` variable in plugin after the `role()` method for now. At least we'd have a way to reload the translations.

```
$role = kirby()->user()->role();
\Kirby\Toolkit\I18n::$translations = [];
```

**Comment by lukasbestle** [comment] 2019-08-05 19:01
Yes, it's definitely coming soon. I was only waiting for some more feedback, but I think it's ready for implementation now.
