### ISSUE TITLE
Hangs if canceled while drag/drop

### ISSUE THREAD

**Issue by afbora** [getkirby/kirby#2981] opened 2020-12-08 17:27 UTC
**To Reproduce**  
1. Create blocks field
2. Add new gallery block
3. Upload images
4. Press the escape key while dragging the image
5. See weird issue

1. Create structure field
2. Add new files/pages field
3. Select pages/files in structure field
4. Press the escape key while dragging any item
5. See weird issue

**Screencast**  
![drag-drop](https://user-images.githubusercontent.com/3393422/101518710-568d2b00-3993-11eb-9a26-894751d1b13b.gif)

**Kirby Version**  
3.5.0-rc.5

**Console output**  
No output

**Desktop (please complete the following information):**  
 - Windows 10
 - Chrome 87.0.4280.88

**Comment by bastianallgeier** [comment] 2020-12-09 09:13
Nice effect 🙈
Could be an issue with the mouseup trap in the drawer.

**Comment by afbora** [comment] 2020-12-09 10:17
I'm not sure it's related to mouseup because I press the escape key before mouseup is triggered. I also cleared out the mouseup method in drawer but it's still the same.

I tried to dispatch all `drag` onClose but still same 🤔 

    this.$store.dispatch("drag", null);

**Comment by bastianallgeier** [comment] 2020-12-09 10:50
I have no idea to be honest. It could also be a bug of vuedraggable. I don't think it's actually connected to blocks or the rc in general. I guess we had the same issue before.

**Comment by afbora** [comment] 2020-12-09 11:21
@bastianallgeier You were right. I tried drag and drop another element inside the structure field, the result is the same issue.

![drag-drop-2](https://user-images.githubusercontent.com/3393422/101623633-c9e17c00-3a29-11eb-9c7c-21e9f6a8e615.gif)

**Comment by distantnative** [comment] 2020-12-09 13:13
I think the issue is that the original DOM elements disappear while dragging. So the library wants to re-insert the dragged element but can't find the original list anymore.

**Comment by bastianallgeier** [comment] 2020-12-09 14:28
@distantnative oh, that makes a lot of sense! Maybe there's a chance to intercept the cancel event somehow and fix that in there.

**Comment by bastianallgeier** [comment] 2021-09-22 09:16
There's unfortunately no fix in sight one year later. I'm closing it. If it turns up again or a solution shows up, we can revisit it.

**Closed as completed by bastianallgeier** 2021-09-22 09:16 UTC
