### ISSUE TITLE
slug() returns umlaut inconsistently

### ISSUE THREAD

**Issue by kosmar** [getkirby/kirby#2395] opened 2020-01-15 11:30 UTC
Kirby:     3.3.1
(sry if reported already)

quick example form my working code

so, the h2() is `ö`

```
<?php $items = $page->competence()->toPage()->pagesections()->toStructure(); foreach ($items as $item): ?>
<?php $tabslug = $item->h2()->slug() ?>
<?php endforeach ?>
```

$tabslug is `o`

```
<?php $items = $page->competence()->toPage()->pagesections()->toStructure(); foreach ($items as $item): ?>
<?php $tabslug = $item->h2()->slug() ?>
<?php echo t('thisbreakstheumlaut', '') ?>
<?php endforeach ?>
```

$tabslug is `oe`

can you confirm?

**Comment by distantnative** [comment] 2020-01-15 11:42
I think it's a duplicate of https://github.com/getkirby/kirby/issues/2230

**Comment by kosmar** [comment] 2020-01-15 12:11
seems the same, right. thx.
should i close?

**Comment by afbora** [comment] 2020-01-15 12:11
@distantnative Definitely the same issue with the order in which translations rules are loaded.

**Closed as completed by afbora** 2020-01-15 12:11 UTC
