### ISSUE TITLE
[Panel] Tags Field higher than needed

### ISSUE THREAD

**Issue by wottpal** [getkirby/kirby#575] opened 2018-07-06 14:11 UTC
<img width="364" alt="bildschirmfoto 2018-07-06 um 16 10 44" src="https://user-images.githubusercontent.com/3930150/42383332-37105110-8137-11e8-8bda-3e0b18dcdb5b.png">

**Comment by jenstornell** [comment] 2018-07-06 14:28
Duplicate of https://github.com/k-next/kirby/issues/562

**Closed as completed** 2018-07-06 15:47 UTC
