### ISSUE TITLE
[Panel] Structure sort handles overlap other field columns

### ISSUE THREAD

**Issue by REHvision** [getkirby/kirby#847] opened 2018-08-07 13:16 UTC
When using columns, the space between sections is wide enough for sort handles of pages, files or structures (when used in separate field sections).

The space between fields inside one field section is smaller (what is good when not using structures).
But when using a structure field next to another field inside a field section, the sort handles overlap the other field.

![structure sort handles inside field section](https://user-images.githubusercontent.com/2584674/43778018-cc187c16-9a54-11e8-8946-dff69c423898.png)

**Comment by wottpal** [comment] 2018-08-08 07:40
Duplicate of https://github.com/k-next/kirby/issues/728

**Closed as completed by wottpal** 2018-08-08 07:40 UTC

**Comment by REHvision** [comment] 2018-08-08 10:02
I searched the issues for something similar but didn't find this one :sweat_smile:
