### ISSUE TITLE
srcset() generating more images than necessary

### ISSUE THREAD

**Issue by jnetzlr** [getkirby/kirby#2444] opened 2020-02-12 10:07 UTC
Here's the scenario:

```
'thumbs' => [
  'srcsets' => [
    'default' => [720, 960, 1440, 2880]
  ]
],
```

Optimized image uploaded to Kirby: img.jpg at 2000*1500px, 352kb

srcset() will generate the following:

`<img src="img.jpg" srcset="img-720x.jpg 720w, img-960x.jpg 960w, img-1440x.jpg 1440w, img-2880x.jpg 2880w" sizes="100vw" alt="">`

As you can see there's img-2880x.jpg, downloading the image:
img-2880x.jpg at 2000*1500px, **405kb**

srcset() should have created:
`<img src="img.jpg" srcset="img-720x.jpg 720w, img-960x.jpg 960w, img-1440x.jpg 1440w, img.jpg 2880w" sizes="100vw" alt="">`

And it's worse with png. Tested with a heavily optimized img.png at **993kb**. With the same scenario img-2880x.png is now at **2.9mb**.

**Comment by distantnative** [comment] 2020-10-03 21:34
Basically duplicate of https://github.com/getkirby/kirby/issues/2071 (or not exactly but solving https://github.com/getkirby/kirby/issues/2071 will solve this one too).

**Closed as completed by distantnative** 2020-10-03 21:34 UTC
