### ISSUE TITLE
Long words and urls won’t get cut off correctly in read-only tables (panel)

### ISSUE THREAD

**Issue by tpmatthes** [getkirby/kirby#3244] opened 2021-04-15 11:39 UTC
**Describe the bug**  
If you have a read-only table with long urls in the panel, the content won’t get cut off correctly.

**To Reproduce**  
1. Create a blueprint with a table field that can’t be translated.
2. Add a url field to the entries and use its content for the row preview.
3. Log in to the panel and add some entries with long urls in the main language.
4. Switch to other languages and wonder why the urls won’t get cut off.

**Expected behavior**  
Some good old “overflow: hidden”

**Screenshots**  
![table](https://user-images.githubusercontent.com/30212990/114862446-d66a4c80-9dee-11eb-88f5-d9f19cb4ac84.png)

**Kirby Version**  
3.5.3.1

**Desktop (please complete the following information):**  
 - OS: macOS
 - Browser: Firefox
 - Version: 87.0

Thanks for your continued work on Kirby, it’s a great cms! 😊

**Comment by distantnative** [comment] 2021-04-15 11:42
Duplicate of https://github.com/getkirby/kirby/issues/3227?

**Comment by afbora** [comment] 2021-04-15 11:43
Yes absolutely the same issue.

**Closed as completed** 2021-04-15 11:49 UTC

**Comment by tpmatthes** [comment] 2021-04-15 11:58
Oh yes, that’s true. Sorry, I searched for “table field” instead of “structure field” and didn’t find the existing issue. Thanks!
