### ISSUE TITLE
Uncaught Exception in FileSessionStore.php

### ISSUE THREAD

**Issue by andreasotto** [getkirby/kirby#2623] opened 2020-05-25 15:55 UTC
**Describe the bug**  
In my opinion that Exception should be caught, therefore it could be seen as bug? (Not sure)

```
PHP Fatal error:  Uncaught Kirby\\Exception\\LogicException: Cannot write to session "xx", because it is not locked in kirby/src/Session/FileSessionStore.php:266\nStack trace:\n#0 kirby/src/Session/Session.php(369): Kirby\\Session\\FileSessionStore->set(1590427246, 'xxx...', 'xxx...')\n#1 [internal function]: Kirby\\Session\\Session->commit()\n#2 {main}\n  thrown in kirby/src/Session/FileSessionStore.php on line 266, referer: https://www......eu/panel/pages/account+profile
```

How can that happen, or what can i do against happening again?

**Comment by lukasbestle** [comment] 2020-05-26 17:22
This is an internal filesystem error that should not occur. But if it does (which can happen when other processes like backup tools etc. access the session files while Kirby writes to them), Kirby cannot recover from this.

Catching the Exception would mean swallowing and ignoring it – which would make sessions unreliable.

Over the last 1.5 years, maybe two or three people have reported this issue and it's unfortunately impossible to reproduce because it depends on the filesystem and external influences. Has this happened to you repeatedly or for the first time?

**Comment by afbora** [comment] 2021-03-03 19:26
Closing due to missing information. Feel free to reopen when you reproduce the issue.

**Closed as completed by afbora** 2021-03-03 19:26 UTC
Labels: needs: information ❓
