### ISSUE TITLE
dump() helper conflicts with Symfony var-dumper

### ISSUE THREAD

**Issue by marijnvdwerf** [getkirby/kirby#1907] opened 2019-07-08 07:53 UTC
**Describe the bug**
I tend to use [`symfony/var-dumper`](https://github.com/symfony/var-dumper) to provide a `dump()` function with a really nice output. When installing it using composer, the kirby definition throws an error:
> **Fatal error:** Cannot redeclare dump() (previously declared in /Users/Marijn/Projects/portfolio/vendor/symfony/var-dumper/Resources/functions/dump.php:18) in /Users/Marijn/Projects/portfolio/kirby/config/helpers.php on line 132

**To Reproduce**
1. Run `composer require symfony/var-dumper`

**Expected behavior**
`dump()` function is wrapped in a `if (!function_exists('dump')) {` to prevent duplicate definitions.

**Kirby Version**
3.2.0

**Comment by lukasbestle** [comment] 2019-07-08 09:27
Duplicate of https://github.com/getkirby/ideas/issues/339.

**Closed as completed by lukasbestle** 2019-07-08 09:27 UTC
